### ISSUE TITLE
Feature request: multithread cleaning

### ISSUE THREAD

**Issue by mathieuchateau** [rsnapshot/rsnapshot#101]
Hello,

when starting job, it may prune old snapshot like through rm-rf : 
[25/Jul/2015:19:15:15] /usr/bin/rm -rf /mypath/snapshots/hourly.1/

It's taking 3 hours on my system (glusterFS behind with tons of small files).
Would it be possible to multithread it, like 1 thread per root folder below hourly.1 ?

**Comment by bebehei** [comment]
IMO this should be rm's job...

There should be also an option `cmd_rm` where you can set rm's path. Write a wrapper script and pass the wrapper to rsnapshot as `cmd_rm`.

I don't like to see such code in the rsnapshot program source. It'll be too buggy. There are too much pitfalls for it.

**Comment by DrHyde** [comment]
Try using lazy deletes. This postpones the delete until all other work is done and the lock is released. Threading won't help, you'll always be IO-bound on the rm.

**Comment by rosenfeld** [comment]
Check if updatedb is running hourly too, as it could be slowing down all I/O. If that is the case, maybe you'll want to skip your back-up directory from the indexing path in mlocate.

**Comment by sam-at-github** [comment]
No chance threaded rm is going to be implemented. @DrHyde, and @bebehei solutions address the issue. Closing.
