### ISSUE TITLE
snapshot_root needs to be defined before backup points

### ISSUE THREAD

**Issue by eleftrik** [rsnapshot/rsnapshot#104]
rsnapshot 1.3.1 on CentOS 6.6

In my `/etc/rsnapshot.conf`:

```
snapshot_root /mnt/nfs/nas/encodia-server/

/mnt/nfs/nas/encodia-server/ is a NFS share on a NAS; it's mounted and writeable (I can rsync to it).
```

If i run `sudo rsnapshot configtest` I get:

```
----------------------------------------------------------------------------
rsnapshot encountered an error! The program was invoked with these options:
/usr/bin/rsnapshot configtest 
----------------------------------------------------------------------------
ERROR: /etc/rsnapshot.conf on line 29:
ERROR: snapshot_root /mnt/nfs/nas/encodia-server/ 
ERROR: /etc/rsnapshot.conf on line 198:
ERROR: backup /etc/ localhost/ - snapshot_root needs to be defined before \
         backup points 
ERROR: /etc/rsnapshot.conf on line 200:
ERROR: backup /usr/local/ localhost/ - snapshot_root needs to be defined \
         before backup points 
ERROR: ---------------------------------------------------------------------
ERROR: Errors were found in /etc/rsnapshot.conf,
ERROR: rsnapshot can not continue. If you think an entry looks right, make
ERROR: sure you don't have spaces where only tabs should be.
```

Thank you.

**Comment by bebehei** [comment]
And now tell me, what is your question?

**Comment by eleftrik** [comment]
My question is: why I get the error "snapshot_root needs to be defined before backup points", when snapshot_root is defined?

**Comment by eleftrik** [comment]
To be more clear:

snapshot_root /.snapshots/  -> syntax ok
snapshot_root /mnt/nfs/nas/encodia-server/  -> I get the error I reported

**Comment by bebehei** [comment]
Pls paste your complete (if you wish, you can anonymize it) config, I'll help you.

But TBH, the message is quite obvious.

**Comment by eleftrik** [comment]
Here is the full config file. 

#################################################
# rsnapshot.conf - rsnapshot configuration file #
#################################################
#                                               #
# PLEASE BE AWARE OF THE FOLLOWING RULES:	#
#                                               #
# This file requires tabs between elements	#
#                                               #
# Directories require a trailing slash:         #
#   right: /home/                               #
#   wrong: /home                                #
#                                               #
#################################################

#######################
# CONFIG FILE VERSION #
#######################

config_version  1.2

###########################
# SNAPSHOT ROOT DIRECTORY #
###########################

# All snapshots will be stored under this root directory.
#

snapshot_root /mnt/nfs/nas/encodia-server/

# If no_create_root is enabled, rsnapshot will not automatically create the
# snapshot_root directory. This is particularly useful if you are backing
# up to removable media, such as a FireWire or USB drive.
#
no_create_root  1

#################################
# EXTERNAL PROGRAM DEPENDENCIES #
#################################

# LINUX USERS:   Be sure to uncomment "cmd_cp". This gives you extra features.
# EVERYONE ELSE: Leave "cmd_cp" commented out for compatibility.
#
# See the README file or the man page for more details.
#
cmd_cp          /bin/cp

# uncomment this to use the rm program instead of the built-in perl routine.
#
cmd_rm          /bin/rm

# rsync must be enabled for anything to work. This is the only command that
# must be enabled.
#
cmd_rsync	/usr/bin/rsync

# Uncomment this to enable remote ssh backups over rsync.
#
cmd_ssh         /usr/bin/ssh

# Comment this out to disable syslog support.
#                                                
cmd_logger      /usr/bin/logger

# Uncomment this to specify the path to "du" for disk usage checks.
# If you have an older version of "du", you may also want to check the
# "du_args" parameter below.
#   
cmd_du          /usr/bin/du

# Uncomment this to specify the path to rsnapshot-diff.
#
#cmd_rsnapshot_diff     /usr/local/bin/rsnapshot-diff

# Specify the path to a script (and any optional arguments) to run right
# before rsnapshot syncs files
#
#cmd_preexec    /path/to/preexec/script

# Specify the path to a script (and any optional arguments) to run right
# after rsnapshot syncs files
#
#cmd_postexec   /path/to/postexec/script

#########################################
#           BACKUP INTERVALS            #
# Must be unique and in ascending order #
# i.e. hourly, daily, weekly, etc.      #
#########################################

interval        hourly  6
interval        daily   7
interval        weekly  4
#interval       monthly 3

############################################
#              GLOBAL OPTIONS              #
# All are optional, with sensible defaults #
############################################

# Verbose level, 1 through 5.
# 1     Quiet           Print fatal errors only
# 2     Default         Print errors and warnings only
# 3     Verbose         Show equivalent shell commands being executed
# 4     Extra Verbose   Show extra verbose information
# 5     Debug mode	Everything
#
verbose         2

# Same as "verbose" above, but controls the amount of data sent to the
# logfile, if one is being used. The default is 3.
#
loglevel        3

# If you enable this, data will be written to the file you specify. The
# amount of data written is controlled by the "loglevel" parameter.
#
#
logfile /var/log/rsnapshot

# If enabled, rsnapshot will write a lockfile to prevent two instances
# from running simultaneously (and messing up the snapshot_root).
# If you enable this, make sure the lockfile directory is not world
# writable. Otherwise anyone can prevent the program from running.
# 
lockfile        /var/run/rsnapshot.pid

# Default rsync args. All rsync commands have at least these options set.
# 
#rsync_short_args	-a
#rsync_long_args        --delete --numeric-ids --relative --delete-excluded

# ssh has no args passed by default, but you can specify some here.
# 
#ssh_args	-p 22

# Default arguments for the "du" program (for disk space reporting).
# The GNU version of "du" is preferred. See the man page for more details.
# If your version of "du" doesn't support the -h flag, try -k flag instead.
#
#du_args        -csh

# If this is enabled, rsync won't span filesystem partitions within a
# backup point. This essentially passes the -x option to rsync.
# The default is 0 (off).
# 
#one_fs         0

# The include and exclude parameters, if enabled, simply get passed directly
# to rsync. If you have multiple include/exclude patterns, put each one on a
# separate line. Please look up the --include and --exclude options in the
# rsync man page for more details on how to specify file name patterns.
#
#include        ???
#include        ???
#exclude        ???
#exclude        ???

# The include_file and exclude_file parameters, if enabled, simply get
# passed directly to rsync. Please look up the --include-from and
# --exclude-from options in the rsync man page for more details.
# 
#include_file   /path/to/include/file
#exclude_file   /path/to/exclude/file

# If your version of rsync supports --link-dest, consider enable this.
# This is the best way to support special files (FIFOs, etc) cross-platform.
# The default is 0 (off).
# 
#link_dest	0

# When sync_first is enabled, it changes the default behaviour of rsnapshot.
# Normally, when rsnapshot is called with its lowest interval
# (i.e.: "rsnapshot hourly"), it will sync files AND rotate the lowest
# intervals. With sync_first enabled, "rsnapshot sync" handles the file sync,
# and all interval calls simply rotate files. See the man page for more
# details. The default is 0 (off).
# 
#sync_first     0

# If enabled, rsnapshot will move the oldest directory for each interval
# to [interval_name].delete, then it will remove the lockfile and delete
# that directory just before it exits. The default is 0 (off).
#
#use_lazy_deletes       0

# Number of rsync re-tries. If you experience any network problems or
# network card issues that tend to cause ssh to crap-out with
# "Corrupted MAC on input" errors, for example, set this to a non-zero
# value to have the rsync operation re-tried
# 
#rsync_numtries 0

###############################
### BACKUP POINTS / SCRIPTS ###
###############################

# LOCALHOST
#backup /home/          localhost/
backup  /etc/           localhost/
backup  /usr/local/     localhost/

#backup /var/log/rsnapshot              localhost/
#backup /etc/passwd     localhost/
#backup /home/foo/My Documents/         localhost/
#backup /foo/bar/       localhost/      one_fs=1, rsync_short_args=-urltvpog
#backup_script  /usr/local/bin/backup_pgsql.sh  localhost/postgres/

# EXAMPLE.COM
#backup_script  /bin/date "+ backup of example.com started at %c"	unused1
#backup root@example.com:/home/ example.com/    +rsync_long_args=--bwlimit=16,exclude=core
#backup root@example.com:/etc/  example.com/    exclude=mtab,exclude=core
#backup_script  ssh root@example.com "mysqldump -A > /var/db/dump/mysql.sql"    unused2
#backup root@example.com:/var/db/dump/  example.com/
#backup_script  /bin/date	"+ backup of example.com ended at %c"   unused9

# CVS.SOURCEFORGE.NET
#backup_script  /usr/local/bin/backup_rsnapshot_cvsroot.sh      rsnapshot.cvs.sourceforge.net/

# RSYNC.SAMBA.ORG
#backup rsync://rsync.samba.org/rsyncftp/	rsync.samba.org/rsyncftp/

**Comment by bebehei** [comment]
I cannot reproduce.

This error-message is the important one. Please rewrite the line and check for bad characters in the file.

At line 29 rsnapshot does not get the snapshot_root variable correct. Therefore your backup-point will mock up and tell you you haven't got a valid `snapshot_root`.

```
ERROR: /etc/rsnapshot.conf on line 29:
ERROR: snapshot_root /mnt/nfs/nas/encodia-server/
```

**Comment by eleftrik** [comment]
Thanks for your support. 
I rewrote the line, but the error is the same. No bad characters.
As I said, the directory is an NFS mount. Could it be related?

df   shows:

...
192.168.1.10:/backup 3860540000 1375082432 2485457568  36% /mnt/nfs/nas

I am root, I can cd or create files in /mnt/nfs/nas/encodia-server/

**Comment by bebehei** [comment]
I tested it with an NFS mount, but NFS works without any problems.

**Comment by eleftrik** [comment]
Maybe there is something wrong with my NFS mount? Is there any particular prerequisite for rsnapshot to work with such a mount?

**Comment by eleftrik** [comment]
rsync /tmp/foo.txt /mnt/nfs/nas/encodia-server/
works with no problems.

**Comment by eleftrik** [comment]
My fault. I used a space instead of a tab, between snapshot_root and the value.
Thanks for your support.
