### ISSUE TITLE
Destructive rotations, redux.

### ISSUE THREAD

**Issue by GrumpyDave** [rsnapshot/rsnapshot#107]
This may be an extension to issue # 33 [https://github.com/rsnapshot/rsnapshot/issues/33], but I want to simplify the description.

With sync_first enabled, running rsnapshot for any retain interval will rotate and delete the backups even if there's no newer backup to take their place.  This eventually leads to every backup being removed.

For example, if you have this in rsnapshot.conf:
retain  weekly  3
And then run "rsnapshot weekly" three times all your weekly backups will be gone.

rsnapshot should not rename any backup to X+1 unless there's an X-1 (or .sync) being promoted.  When X+1 hits the retain value the backup is deleted whether or not any more recent backups exist.

Scheduling the rsnapshot cron jobs as described right on the man page leaves the daily, weekly, and monthly rotations vulnerable to this because they're not dependent on a successful sync job.

**Comment by sam-at-github** [comment]
Your right, its an issue. I think this change is planned for 1.5. See #92.
