### ISSUE TITLE
ignores all changes on ntfs to ext4

### ISSUE THREAD

**Issue by DimensionalScoop** [rsnapshot/rsnapshot#108]
When using rsnapshot to back up a directory on a ext4 partition and a directory on a ntfs partition to an external hard drive (also ext4), all changes in the ntfs directory are just ignored.

**Comment by bebehei** [comment]
In general, this is a "problem" of rsync. You just need to adapt the rsync options in rsnapshot. I never had to adapt this to an MS-based filesystem. For more help, ask on the mailing-list. https://lists.sourceforge.net/lists/listinfo/rsnapshot-discuss
