### ISSUE TITLE
Ignore git working directory

### ISSUE THREAD

**Issue by Yamakaky** [rsnapshot/rsnapshot#109]
Did you consider adding an option for not saving the content of a directory when it's a git repo, and only save .git/ ? .git already contains the history of the project. It may be difficult to implement using rsync, though.

**Comment by sam-at-github** [comment]
No. That would be a strange and not very useful thing to do IMO. Your backup would be contingent on someone having done a commit recently.

**Comment by bebehei** [comment]
No, we don't consider this. If you want to ignore your working-tree from git, you have to use the `exclude_file` option.

Why we don't do this?
- What happens to changes if you had been working in your working tree and they had been uncommited during backup?
- another thing: KISS. rsnapshot defines itself as a filesystem backup utility. Nothing more. Why should we add anything which ignores the git-working tree? How do we assure that noone will be affected badly by this change?

For me, to produce such a behavior is part of the configuration and **not** part of the software. Options to configure. to trigger such a behavior are already in rsnapshot.

**Comment by bebehei** [comment]
the last sentence completed:  To trigger such a behavior, there are already options for this in rsnapshot.

E.g.
```
exclude_file /path/to/exclude
include_file /path/to/include

backup_script find-gitfolders.sh dummybackup/
backup /your/original/backup backup/
```

Now you have to write the script `find-gitfolders.sh` which fills the exclude and include-files with the specific git-repositories. The logic in find-gitfolders.sh is up to you.
