### ISSUE TITLE
Root is created before preexec

### ISSUE THREAD

**Issue by lightonflux** [rsnapshot/rsnapshot#112]
This is not necessarily a bug but very unexpected or unfortunate for some NAS related use cases. A papercut if you want.

The situation: 

The `snapshot_root` should be on a NAS. But the nas is powered off all the time, started via wake-on-lane and mounted with a preexec script.

 * rsnapshot version 1.3.1 from Debian Wheezy.

Here the relevant parts of the config in the right order. But it does not matter if `snapshot_root` is before `cmd_preexec` or not. 

	config_version	1.2

	snapshot_root	/mnt/nas-03/rsnapshot-backup

	cmd_preexec	/root/wakup-and-mount-nas03.sh
	cmd_postexec	/root/umount-nas03.sh

When i test the config with option -t i get the following sequence of commands:

	root@atlas:/# rsnapshot -c /etc/rsnapshot-auf-nas03.conf -t daily
	echo 27062 > /var/run/rsnapshot-nas03.pid 
	mkdir -m 0700 -p /mnt/nas-03/rsnapshot_backup/ 
	/root/make-nas03-ready.sh
	mkdir -m 0755 -p /mnt/nas-03/rsnapshot_backup/daily.0/ 
	/usr/bin/rsync -a --delete --numeric-ids --relative --delete-excluded /home \
	    /mnt/nas-03/rsnapshot_backup/daily.0/atlas/ 
        […] all the folders
	touch /mnt/nas-03/rsnapshot_backup/daily.0/ 
	/root/umount-nas03.sh

What happens is that `snapshot_root` is created in `/mnt/mountpoint/snapshot_root` then preexec runs and mounts the storage above the snapshot_root. Now the folder is not accessible and gets created on the NAS by `mkdir … -p mnt/mountpoint/snapshot_root/daily.0/` anyway. This leaves an orphaned folder in `/mnt/mointpoint/` called `snapshot_root` which is never used and only visible if the storage is unmounted. 

IMHO preexec should be executed before rsnapshot writes any file related to storing the backup.

**Comment by sam-at-github** [comment]
Yeah but there are potential problems either way  - what if some pre_exec script depends on the snapshot root being created -- I'm sure such a script is in existence somewhere. So ... it's not really worth change this.
In my setup I wrap the calls to rsnapshot in script that mounts a back drive:

    #!/bin/bash

    function fail() {
      echo "$@"; exit 1;
    }

    function post() {
      ./backups-post || fail "Post failed"
    }

    cd `dirname $0`
    trap "post" EXIT
    ./backups-pre || fail "Pre failed. Will not continue"
    [[ -d /backups ]] || fail "Backup desination does not exist. Will not create it"
    rsnapshot -c /etc/backups-rsnapshot/backups-rsnapshot.conf sync && rsnapshot -c /etc/backups-rsnapshot/backups-rsnapshot.conf level0
