### ISSUE TITLE
Consider Hostname for rotation

### ISSUE THREAD

**Issue by nazco** [rsnapshot/rsnapshot#115]
If I backup from two hosts to the same snapshot_root on an NFS share, the two instances interfere each other. As example: I installed a new host and want to run rsnapshot for the first time. My expected behavior was, that rsnapshot would create another subfolder named like the hostname under, for example, the folder daily.0 and not to work directly on the daily.0 folder. So at the moment the new host would delete the daily.6 folder and start the rotation, this is not the behavior I would expect. It would be great if the rotation task would be aware of the different host names and only rotate the correct folders.

**Comment by bebehei** [comment]
Sry in advance: I can't get a clear overview of your problem. My solution would be like this:

Either use to backup-lines like this:
```
backup user@host1:/your/path/you/want/to/save host1
backup user@host2:/your/path/you/want/to/save host2
# replace spaces with tabs!
````

or make use of another rsnapshot.conf-file (this is my recommendation).

**Comment by nazco** [comment]
Ok, I'll try to explain it:
In your example everything works because this config file would be used on ONE Host.
In my config (host1) I use: 
`backup /home host1`
on host2 I use the same command except the host name.

So if I run the command on host1 and after that on host2 it breaks.

**Comment by bebehei** [comment]
Mir dünkt Schlechtes.

Please paste your full config.

**Comment by nazco** [comment]
Dann gucken ma doch mal.
The only difference between the two hosts is the different host name at the end.
https://paste.noname-ev.de/7451

**Comment by bebehei** [comment]
Do hän i mol noguggt ond i moin:

So you backup on a shared storage but don't share your lockfile?

**Comment by bebehei** [comment]
Oh wait: you backup from two different hosts? Sry my previous statement was completely wrong. You have to use two different snapshot_roots on your NFS storage.

**Comment by bebehei** [comment]
After looking over the stuff again on my laptop, I can definitely say, you have to use two different `snapshot_root`s. My first comment suggesting two backup-dirs is invalid.

And sorry no, there is no possibility to add such a host-flag. rsnapshot's design denies this.

If you've got other questions, ask them here or on `rsnapshot-discuss`, the mailinglist. You can signup here: https://lists.sourceforge.net/lists/listinfo/rsnapshot-discuss

If there is nothing left, please close the issue. Thanks.
