### ISSUE TITLE
ERROR: /usr/bin/rsync returned 0.09375

### ISSUE THREAD

**Issue by tuxick** [rsnapshot/rsnapshot#118]
cron was mailing me these crazy error messages, turned out the code does "return ($retval / 256);
" for some reason. Is there any reason for obfuscating rsync return values?

**Comment by Jo-Con-El** [comment]
This is due to the fix for #102, which did the bitwise operation on the result exit code (>> 8) twice.  Specifically e3c299db7b564b9668758adc3ccd4a3c3226c3af, forcing that even though we do it on line 3929, a bit later.  I'll submit a PR.

**Comment by Jo-Con-El** [comment]
#114 has been written to cover this, but it breaks Continuous integration because I suspect that we need another fix.

**Comment by sam-at-github** [comment]
Fixed. Will merge into master shortly.
