### ISSUE TITLE
Custom RM-command still uses -rf arguments

### ISSUE THREAD

**Issue by m3nu** [rsnapshot/rsnapshot#120]
I'm using s3ql as backup drive. This is a wrapper around Amazon S3.

It works like a normal drive, but `rm -rf` is fairly slow because there is a lot of overhead involved.

For that reason the authors offer a custom `s3rm` command which is considerably faster.

I'd like to sue `s3rm` with `rsnapshot`. The issue is that even after specifying a custom `cmd_rm`, it still uses the `rm`-specific `-rf` args.

Expected behavior would be:

- set custom `cmd_rm`
- `rsnapshot` calls exactly that command without added `-rf` or other args.

What do you think? I will do a PR, if you agree this is useful.

**Comment by manuelRiel** [comment]
PS: Same issue with `cp -al`

**Comment by bebehei** [comment]
`cmd_rm` only sets the command, not the arguments :wink: 

To fulfill your demands we would need another options like `rm_flags`.

Possible quickfix:
```
#!/bin/bash
s3rm $(echo $* | sed 's/-rf//g')
```
