### ISSUE TITLE
Different rotation for local rsnapshot snapshot_root and remote rsync server

### ISSUE THREAD

**Issue by eriksenonline** [rsnapshot/rsnapshot#125]
This might be a future request if I have not misunderstood something.

Many times a local server / webserver etc. have little space on the disks. Like me I would like to be able to set up rsnapshot with ssh but with different data on the remote and local snapshot_root.

Example: If I run a backup server and have a local snapshot_root, I would like to only keep the lastes backup and not the previous 6 days. So when I do a backup the latest and only that will stay in my local snapshot_root and all other will be moved to a remote offsite archive like amazon or another remote server.

Is this at all possible to do?

**Comment by sam-at-github** [comment]
Hi @eriksenonline. If your asking: I want rsnapshot to intelligently discvier that there is no diskspace left then decide to store snapshots somewhere else. Then no. 

If you only want one image on your local, do an `rsync` or `cp -al` or what ever to some place. Then from the remote server do an rsnapshot of that image via SSH. You will have to ensure your local script and remote rsnapshot script are not stepping on each other's toes. You could use a lock file.
