### ISSUE TITLE
security of running rsnapshot as root

### ISSUE THREAD

**Issue by timkuijsten** [rsnapshot/rsnapshot#126]
Given the recent [rsync vulnerability](https://rsync.samba.org/security.html#s3_1_2) I wonder what the best practice is to run rsnapshot. I used to run rsnapshot as root on the backup host, because only then all file modes and ownership are transferred correctly and no permission problems arise*. But that would make the backup machine vulnerable to any compromised production servers that are being backed up, right?

So I wonder if people are running rsnapshot as a non-root user in order to mitigate bugs in rsnapshot/rsync and choose to loose all permission and ownership info, use tar, or maybe have a better way to handle backups?

&nbsp;* I've learned that the permission problem might be solved by using `rsync --chmod=u+rwX`

**Comment by sam-at-github** [comment]
Please raise this on the mailing list. Would be an interesting discussion.

**Comment by timkuijsten** [comment]
https://sourceforge.net/p/rsnapshot/mailman/rsnapshot-discuss/?viewmonth=201604&viewday=21&style=threaded
