### ISSUE TITLE
autogen.sh error

### ISSUE THREAD

**Issue by m-osmani** [rsnapshot/rsnapshot#127]
git describe --tags --always --dirty
1.4.2-dirty
---------------------------------------------------------------------------
Distributor ID: CentOS
Description:    CentOS release 6.7 (Final)
Release:        6.7
Codename:       Final

./autogen.sh
configure.ac:1: error: possibly undefined macro: m4_esyscmd_s
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

I dont know what causes this error.

regards

**Comment by bebehei** [comment]
As usual on CentOS, there something is too old. And here it is autoconf.

Either
- grab a release tarball with prebuilt configure
- build it via git and remove the `m4_esyscmd_s` macro call as follows:
```
diff --git a/configure.ac b/configure.ac
index ea69b82..917477d 100644
--- a/configure.ac
+++ b/configure.ac
@@ -1,4 +1,4 @@
-AC_INIT([rsnapshot],[m4_esyscmd_s([git describe --tags --always --dirty])],[rsnapshot-discuss
+AC_INIT([rsnapshot],[1.4.2-gitbuild-centos],[rsnapshot-discuss@lists.sourceforge.net])
 AM_INIT_AUTOMAKE([foreign])
 AC_PROG_MAKE_SET
 AC_CONFIG_FILES(Makefile)
```

**Comment by m-osmani** [comment]
Thx a lot!
