### ISSUE TITLE
rsnapshot 1.4.2 is missing from http://rsnapshot.org/downloads/

### ISSUE THREAD

**Issue by pahi** [rsnapshot/rsnapshot#129]
It seems that rsnapshot 1.4.2 is missing from http://rsnapshot.org/downloads/
The latest version mentioned on the site is 1.4.1. Should be an easy fix.

**Comment by sam-at-github** [comment]
Yeah that's my bad. There was a bug in 1.4.1 that a number of people were bringing up. Fixed it, and tagged a new release, but didn't go through the full update. I probably should have tagged it 1.4.1rc, or not at all. Maybe we should rename it now. @bebehei?

**Comment by AMDmi3** [comment]
Won't it be better to properly release 1.4.2 instead as it fixes the bug?

**Comment by bebehei** [comment]
@pahi @sam-at-github Yes, I will do!

@AMDmi3 [CONTRIBUTING.md](https://github.com/rsnapshot/rsnapshot/blob/master/CONTRIBUTING.md#releases-and-versions)

**Comment by bebehei** [comment]
@pahi Thanks for reporting it. It's uploaded and cache got the update already.
