### ISSUE TITLE
hourly snapshots cmd_preexec

### ISSUE THREAD

**Issue by masterofamn** [rsnapshot/rsnapshot#130]
I would like to report an issue I realized in my rsnapshot setup: I have my snapshots on a usually ro mounted disk which by cmd_preexec/cmd_postexec gets mounted rw only for the duration of the snapshot. While this works for hourly tasks, this fails for daily tasks because the mv command to save the daily snapshot is executed before cmd_preexec:

Hourly:

`/usr/users/usr/bin/rsnapshot hourly: started `
`echo 28984 > /scratch/rsnapshot.pid`
`/masterofamn/bin/mo <= MOUNT RW`
`/bin/rm -rf /backup/snapshot/hourly.5/`
`mv /backup/snapshot/hourly.4/ /backup/snapshot/hourly.5/`
`mv /backup/snapshot/hourly.3/ /backup/snapshot/hourly.4/`
`mv /backup/snapshot/hourly.2/ /backup/snapshot/hourly.3/`
`mv /backup/snapshot/hourly.1/ /backup/snapshot/hourly.2/`
`/bin/cp -al /backup/snapshot/hourly.0 /backup/snapshot/hourly.1`
`/usr/bin/rsync [....]`
`touch /backup/snapshot/hourly.0/`
`/usr/users/masterofamn/bin/um <= MOUNT RO`
`rm -f /scratch/rsnapshot.pid`
`/usr/bin/rsnapshot hourly: completed successfully`

Daily:

`/usr/bin/rsnapshot daily: started`
`echo 29045 > /scratch/rsnapshot.pid`
`mv /backup/snapshot/hourly.5/ /backup/snapshot/daily.0/`
`/usr/bin/rsnapshot daily: ERROR: Could not rename("/backup/snapshot/hourly.5", "/backup/snapshot/daily.0")`
`/usr/bin/rsnapshot daily: ERROR: Error! safe_rename("/backup/snapshot/hourly.5/", "/backup/snapshot/daily.0/")`
`rm -f /scratch/rsnapshot.pid`

**Comment by bebehei** [comment]
Yes, this is correct. According to the documentation, it'll only execute before the so-called sync operations:

> cmd_preexec:
> Full path (plus any arguments) to preexec script (optional).  This script will run immediately before each backup operation (but not any rotations). [...]

Sry for the late reply. Please paste your question next time on the general [rsnapshot-discuss ML](https://lists.sourceforge.net/lists/listinfo/rsnapshot-discuss). There are more users "listening" to you.
