### ISSUE TITLE
config file white spaces

### ISSUE THREAD

**Issue by garrett85** [rsnapshot/rsnapshot#131]
Please modify rsnapshot to allow any number or type of what spaces between arguments. I have vi set to input 4 spaces instead of a tab when I press TAB for coding purposes. Even using vi's 'Y - Yank' and 'P - Put' commands I could net get a successful test run for rsnapshot. I had to modify an existing example line just to get my backup directory to work without error.

**Comment by marcin-gryszkalis** [comment]
I wouldn't care if rsnapshot was written in C - but hey, it's perl - the greatest parsing language on this planet. It's a shame to force such requirements for perl application ;)

Anyway - I guess tab was chosen for separator to allow more robust usage of spaces in paths - but I'd call to check if it can be changed while retaining 99.99% backward compatibility.

**Comment by sam-at-github** [comment]
Dups #117. Please check to see if the issue has been raised before creating new issue. Closed.
