### ISSUE TITLE
rsnapshot.pid: Permission denied

### ISSUE THREAD

**Issue by garrett85** [rsnapshot/rsnapshot#135]
Here's my setup. I have rsnapshot installed on my Mint desktop and I I have two backup locations set in /etc/rsnapshot.conf, hone is my home directory on my Mint desktop, /home/user/, and the other is my media library on my headless debian media server garrett@IP.ADDRESS:/home/garrett/media/, and my snapshot_root is set to /backup on my desktop which is sshfs mounted to my 5 TB HDD on my raspberry pi 2. So here my config settings:

snapshot_root   /backup
-->drwxrwxrwx   1 root root  4096 Mar  4 22:44 backup <- `ls /`
-->pi@192.168.1.140:/media/pi/backupdrive  4.6T  1.0T  3.3T  24% /backup <- `df -h`

retain      hourly  2
retain      daily   2
retain      weekly  1
retain      monthly 1

backup  /home/garrett/      localhost/
exclude /home/garrett/.local/share/Trash/
exclude /home/garrett/.cache/
exclude /home/garrett/.Trash*
backup  garrett@192.168.1.150:/home/garrett/media/      192.168.1.150/

When I run `rsnapshot testconfig` I get
----------------------------------------------------------------------------
rsnapshot encountered an error! The program was invoked with these options:
/usr/bin/rsnapshot testconfig 
----------------------------------------------------------------------------

and when I run `rsnapshot -t daily` this is that I get.

echo 16121 > /var/run/rsnapshot.pid 
/backup/hourly.1 not present (yet), nothing to copy

Any ideas. I've been trying to get a back incremental snapshot type backup of my desktop and media server for several months now but I havent' had any luck. I gave up on backuppc and now I'm starting to lose hope with rsnapshot.

One last thing. Please start allowing spaces in the config file. My vi is setup for coding so it inserts 4 spaces for every tab, this caused me a lot of trouble. Thanks.

**Comment by sam-at-github** [comment]
Firstly  please raise Qs like this on the mailing list. If you raise this on the mailing list you will get an almost immediate response.

Secondly, yeah there's a number of things wrong with what your trying to do:

  1. I don't think you pasted the full error output from "rsnapshot testconfig"
  1.1 if its saying somethign about a .pid, its trying to do a backup nad needs to be run as root.
   2. AFAIK "testconfig" is not an rsnapshot command!
   3. The output is correct for `rsnapshot -t daily`. Only the lowest level actually does a backup. The rest just rotate. Also recommend you use `sync_first`.
