### ISSUE TITLE
Retry grace time

### ISSUE THREAD

**Issue by ISibboI** [rsnapshot/rsnapshot#137]
I have an SSH-DDoS-protection for my server, which prevents single IPs from connecting too often via ssh. Due to my weak network connection I need to set rsync_numtries to 1000 to get a backup done. But even then it doesn't always work, because if the connection fails too often in a short period of time, the DDoS-protection triggers and ignores my IP for some time.

I'd be happy if there was an retry grace time option, with which I can tell rsnapshot to wait x seconds before restarting rsync.

**Comment by sam-at-github** [comment]
I don't think this option i viable or necessary. You could try using  `cmd_rsync`, `rsync_long|short_args` options to achieve aims.

Also you could just poke a hole in you FW for your rsync job. Surely you are not going to be DDOSd from you backup server.

**Comment by ISibboI** [comment]
The backup server has a dynamic IP, which makes that pretty difficult.
I could create a script that waits a minute before invoking rsync, but to me that seems to be a strange way to do stuff.
Anyway, I solved that problem by allowing a higher amount of connections per minute to my server. Seems to work.
