### ISSUE TITLE
Paths to LVM snapshots are broken

### ISSUE THREAD

**Issue by andymwood** [rsnapshot/rsnapshot#146]
I'm running rsnapshot under OpenSUSE 13.2

rsnapshot.conf has the following lines:

```
linux_lvm_cmd_lvcreate  /sbin/lvcreate
linux_lvm_cmd_lvremove  /sbin/lvremove
linux_lvm_cmd_mount /usr/bin/mount
linux_lvm_cmd_umount    /usr/bin/umount
linux_lvm_snapshotsize  2G
linux_lvm_snapshotname  rsnapshot
linux_lvm_vgpath    /dev
linux_lvm_mountpath /mnt/lvm-rsnapshot
backup  lvm://mapper/system-home/source  target
```

I get the following error message when I run rsnapshot:

> ERROR: Mount LVM snapshot failed: 8192
>   Volume group "rsnapshot" not found
>   Skipping volume group rsnapshot
> ERROR: Removal of LVM snapshot failed: 1280

If I run rsnapshot with the '-t' option, I get:

> /sbin/lvcreate --snapshot --size 2G --name rsnapshot \
>     /dev/mapper/system-home 
> /usr/bin/mount /dev/mapper/rsnapshot /mnt/lvm-rsnapshot 
> ...
> /usr/bin/umount /mnt/lvm-rsnapshot 
> /sbin/lvremove --force /dev/mapper/rsnapshot

So, it looks like rsnapshot is expecting '/dev/mapper/rsnapshot', but no such LVM volume exists. Instead I get '/dev/mapper/system-rsnapshot'.

I've also tried replacing
```
linux_lvm_vgpath    /dev
backup  lvm://mapper/system-home/source  target
```
with
```
linux_lvm_vgpath    /dev/mapper
backup  lvm://system/home/source  target
```
but that doesn't work either.

**Comment by sam-at-github** [comment]
> So, it looks like rsnapshot is expecting '/dev/mapper/rsnapshot'

And rightly so. 

So just to clarify, if you were to run `/sbin/lvcreate --snapshot --size 2G --name rsnapshot /dev/mapper/system-home` in isolation on your system you get a volume called "/dev/mapper/system-rsnapshot"?? That's weird. Try deleting /dev/mapper/system-rsnapshot (given it is actually a snapshot volume) just to be sure its not from somewhere else.

Also please post `lvdisplay  | grep -i snapshot`.

**Comment by andymwood** [comment]
> So just to clarify, if you were to run /sbin/lvcreate --snapshot --size 2G --name rsnapshot /dev/mapper/system-home in isolation on your system you get a volume called "/dev/mapper/system-rsnapshot"?? That's weird.

Yes, that's exactly what's happening:
```
> ls /dev/mapper
system-home  system-root  system-swap
>  /sbin/lvcreate --snapshot --size 2G --name rsnapshot /dev/mapper/system-home
> ls /dev/mapper
system-home  system-home-real  system-root  system-rsnapshot  system-rsnapshot-cow  system-swap
```

```
> lvdisplay | grep -i snapshot
  LV snapshot status     source of
                         rsnapshot [active]
  LV Path                /dev/system/rsnapshot
  LV Name                rsnapshot
  LV snapshot status     active destination for home
  Allocated to snapshot  0.27%
  Snapshot chunk size    4.00 KiB
```

Aha! That's the solution: replace `lvm://mapper/system-home/source` with `lvm://system/home/source`. Those multiple symbolic links to all the entries in /dev is confusing.

Many thanks.
