### ISSUE TITLE
Restore lvm drives 

### ISSUE THREAD

**Issue by piflixe** [rsnapshot/rsnapshot#148]
Hi there! 
This might be a stupid concern nut I couldn't find an answer yet after hours of googling on that subject. I have virtual machines running on seperate lvm volumes with xen and try to use rsnapshot to do regular incremental backups. This works fine. I just can't find any instructions on how to restore a whole lvm volume from the backup. 
I would be relieved if someone could give me a hint! Thanks. 
Kind regards

**Comment by bebehei** [comment]
rsnapshot does not backup LVM volumes directly. rsnapshot can use LVM to backup with higher consistency. rsnapshot only backs up your files.

rsnapshot will
1. create an LVM snapshot
2. mount the LVM snapshot
3. backup the mountpoint
4. unmount
5. destroy the LVM snapshot

At the end of the day, your backup contains all files from the VM, but no information about the filesystem nor the LVM volume. If you have to restore your LVM volume, you'll have to create a new one, format it and copy the files over.

**Comment by piflixe** [comment]
So I am right in the assumption that rsnapshot does not provide any recovery functionality for lvm?
Could you give me an example on how to do what you described above? Or paste a useful link?
thanks!

**Comment by bebehei** [comment]
rsnapshot does not provide any restoration tool at all. You've got your `snapshot_root`, below that are folders named like `<interval>.<number>` (e.g: `alpha.0`)

Below that dir, there are your separate backuppoints which display your `backup` declarations of rsnapshot.conf. You can copy all files out with plain rsync or other unix tools.

This gives you complete flexibility and endless ways to restore, but you have to care about the restoration for yourself.

I neither know your system nor your backup structure to give you a out of the box tutorial to use.

**Comment by piflixe** [comment]
OK thanks for your comments. Was suprised how fast I get a qualified and detailed answer! I will go for rsync for restore.
