### ISSUE TITLE
Documentation bug: HOWTO not found

### ISSUE THREAD

**Issue by jk-1** [rsnapshot/rsnapshot#154]
Several places in the documentation references to "HOWTO".
e.g. "If this is your first experience with rsnapshot, you may want to read the rsnapshot HOWTO at http://www.rsnapshot.org/. The HOWTO will give you a detailed walk-through on how to get rsnapshot up and running in explicit detail."

However, there is no HOWTO section in http://www.rsnapshot.org/

On http://rsnapshot.org/faq.html there is link to HOWTO: http://rsnapshot.org/howto/1.2/rsnapshot-HOWTO.en.html#restoring_backups
but this does not lead to anything.
Please put the HOWTO back.

**Comment by kberry** [comment]
just adding my +1 ...

also, in the meantime, fwiw, i found (some version of) the howto at http://rsnapshot.org/rsnapshot/docs/docbook/rest.html (by web searches, not linked from anywhere that i could find).
