### ISSUE TITLE
rsnapshot fails with uninitialized lvm values if lvm backup before file backups

### ISSUE THREAD

**Issue by hogarthj** [rsnapshot/rsnapshot#155]
I had a report on bugzilla with rsnapshot failing with:

Use of uninitialized value $traps{"linux_lvm_mountpoint"} in numeric eq (==) at /bin/rsnapshot line 3937.
Use of uninitialized value $traps{"linux_lvm_snapshot"} in string ne at /bin/rsnapshot line 3937.
Use of uninitialized value $linux_lvm_oldpwd in concatenation (.) or string at /bin/rsnapshot line 3938.
chdir()
Use of uninitialized value $linux_lvm_oldpwd in chdir at /bin/rsnapshot line 3940.
Use of chdir('') or chdir(undef) as chdir() is deprecated at /bin/rsnapshot line 3940.
Use of uninitialized value $traps{"linux_lvm_mountpoint"} in numeric eq (==) at /bin/rsnapshot line 3949.
Use of uninitialized value $traps{"linux_lvm_snapshot"} in string ne at /bin/rsnapshot line 3955.
Use of uninitialized value $src in pattern match (m//) at /bin/rsnapshot line 3971.
Use of uninitialized value $src in concatenation (.) or string at /bin/rsnapshot line 3976.

https://bugzilla.redhat.com/show_bug.cgi?id=1388209

A similar report was found in debian:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=794046

**Comment by jdunn0** [comment]
This bug appears to be what was fixed in the pull request  #111.
