### ISSUE TITLE
Environment variables for paths at /etc/rsnapshot.conf

### ISSUE THREAD

**Issue by serhatcevikel** [rsnapshot/rsnapshot#159]
Rsnapshot is the greatest unix tool for incremental backups. I'd like to propose sth to make it more user friendly:

As far as I see, the /etc/rsnapshot.conf file does not support environment variables for pathnames. For example, I defined the path to the external drive I use for packup purposes into an environment variable and I want to define the snapshot_root path relative to that environment variable.

Maybe a conditional in order to check whether a path in the form of "$..." for snapshot_root exists as an environment variable on the local system after line 643 of rsnapshot-program.pl will suffice.

**Comment by Amzani** [comment]
Maybe using rsnapshot with docker will help you, try this image: https://hub.docker.com/r/scandio/rsnapshot/

```
docker run -v /path/to/source/directory:/source -v /path/to/target/directory:/target scandio/docker-rsnapshot
```

**Comment by bebehei** [comment]
> As far as I see, the /etc/rsnapshot.conf file does not support environment variables for pathnames. For example, I defined the path to the external drive I use for packup purposes into an environment variable and I want to define the snapshot_root path relative to that environment variable.

Check out the `include`-statement in `rsnapshot.conf`. Use multiple configurations and in there include your base-configuration-files. This is way more reliable than using env-variables.
