### ISSUE TITLE
Per backup '--rsh' option

### ISSUE THREAD

**Issue by waltersteinlein** [rsnapshot/rsnapshot#163]
Hi,

I'm trying to backup a couple of hosts where ssh is not always where it's supposed to be (or even named how it's supposed to be). To overcome that issue, I tried to add '--rsh' to rsync_long_args which fails, because rsnapshot always add it's own '--rst' (depending on cmd_ssh) afterwards.
If I disable (i.e. comment out) cmd_ssh in my config file the check fails, of course.
I think a simple fix would be to add the rsync_long_args after '--rst' so a user can always overwrite the defaults on a per backup basis. Currently rsync_long_args_stack is created with whatever is in rsync_long_args and the '--rst' is pushed on top :(

Cheers!

**Comment by waltersteinlein** [comment]
Maybe something like this?

[rsnapshot-program.pl.diff.txt](https://github.com/rsnapshot/rsnapshot/files/678131/rsnapshot-program.pl.diff.txt)

**Comment by sam-at-github** [comment]
Presuming you mean `--rsh` not `--rst`. Rsnaphot has two options for controlling which SSH client is used `cmd_ssh` which should be the full path to an executable, and `ssh_args` which become arguments to that executable. Granted it might be nice to just specify `--rsh` but you can achieve desired result with these two rsnapshot options
