### ISSUE TITLE
no WARNING on stdout with incorrectly quoted backup dir

### ISSUE THREAD

**Issue by shodanshok** [rsnapshot/rsnapshot#167]
My `rsnapshot.conf` have `verbose 2` and `loglevel 3`. From my understanding, `verbose 2` should show both errors and warnings. However, I found a case where no warning are shown on `stdout`, but they can be found on the logfile, even when using `loglevel 2`.

Let say I have a backup dir with space in it and I fail to quote it. For example:
`backup  root@localhost:/opt/fileserver test/    fileserver/`
Executing `rsnapshot -t daily` show no errors, but its return code is `2`:
<pre>
[root@centos-webdev .snapshots]# rsnapshot daily
[root@centos-webdev .snapshots]# echo $?
2
[root@centos-webdev .snapshots]#
</pre>
Moreover, in the log file I can see the following line:
`WARNING: /usr/bin/rsnapshot daily: completed, but with some warnings`

To see a warning on `stdout`, I need to use `verbose 4`, but it seems *too much* verbose.

I am missing something?

**Comment by bebehei** [comment]
Have you rsnapshot 1.3.1?

From [FAQ](http://rsnapshot.org/faq):
> # I have a snapshot root or backup point with a space (or other special character) in it and this is not working at all with rsnapshot 1.3.1. Why?
>
> rsnapshot version 1.3.1 has an issue where the rsync command is interpreted by a shell rather than directly executed by rsnapshot. This bug is expected to be fixed in rsnapshot CVS on 24 March 2009, and so should appear an a forth-coming release (probably version 1.3.2). This bug was not present in rsnapshot 1.3.0.

It should be fixed with latest version.

**Comment by shodanshok** [comment]
Hi, I tried with rsnapshot 1.4.2

Anyway, the problem appear to be more generic: it seems that no WARNING are show the stdout, but the error exit code is `2`.

For example, when backupping a directory with vanishing files (which cause `rsync` to exit with code `24`), no error are show on stdout but the error code raised is `2`, indicating a "dirty" rsnapshot run.

I really think WARNINGS should be printed on stdout.

**Comment by shodanshok** [comment]
After poking around with source code, I found that `rsync` error codes `23` and`24` are considered "minor warnings" and are not shown when `verbose < 4`.

While for error code `24` this is very sane (as rsync run on "live" filesystem often emits spurious "file has vanished" warnings), it is quite dangerous to ignore error code `23`, as the latter is emitted when something prevented `rsync` to fully scan/transfer the source directory.

For example, trying to rsync a non existent or mispelled remote directory (as by the example above) return *no* warnings on the command line, and this is clearly misleading.

I strongly suggest to change line 4202 from `4` to `2`, restoring "normal" warning weight for error code `23`

See pull request #179

**Comment by sgpinkus** [comment]
Merged.
