### ISSUE TITLE
backing up crontabs

### ISSUE THREAD

**Issue by nigelhorne** [rsnapshot/rsnapshot#168]
See $subj.  Is there a neat way of backing up crontabs?

**Comment by cantlep** [comment]
Hi,

You could just backup /var/spool/cron/ (in linux for example) and let it back up all of the files in there? That should sort it.

Rgds

Paul

**Comment by nigelhorne** [comment]
Except that some also go in /etc/cron.* - that was my thinking whether I could say "backup from where-ever works best".

**Comment by cantlep** [comment]
I believe they are considered entirely separate. System stuff in /etc/cron.* and user stuff in /var/spool/cron

I don't think there's a feature in rsnapshot as you describe with a kind of "backup everywhere a crontab might live".





On Mon, Jan 23, 2017 at 7:12 PM +0000, "Nigel Horne" <notifications@github.com<mailto:notifications@github.com>> wrote:


Except that some also go in /etc/cron.* - that was my thinking whether I could say "backup from where-ever works best".

**Comment by bebehei** [comment]
Just define multiple backup sources in your `rsnapshot.conf`. That's all. For further information, please consult [rsnapshot-discuss mailing list](https://lists.sourceforge.net/lists/listinfo/rsnapshot-discuss). There are way more people around.

Regardless of rsnapshot: It's not recommended to have just single files as a "backup". I'd consider backing up complete `/etc/` or `/`.
