### ISSUE TITLE
Exclude all except

### ISSUE THREAD

**Issue by albrin** [rsnapshot/rsnapshot#169]
For four hours trying to configure, but the rsnapshot does not work as I want.

I want to do a full backup of the virtual server, but only the necessary directories and files. Everything else I want to exclude.

For example,
Exclude all subdirectories in a directory **/etc**
except directories and all the files inside them
**/etc/nginx/**
**/etc/php-fpm.d**
**/etc/yum.repos.d**
and **all files in** the directory itself **/etc/**.

**Comment by bebehei** [comment]
Please ask questions next time on [rsnapshot-discuss](https://lists.sourceforge.net/lists/listinfo/rsnapshot-discuss).

[CentOS Manual](https://wiki.centos.org/HowTos/RsnapshotBackups#head-3aa83d72545595821bbbe0dc52b99064fe057901) fits completely your use-case. use a rsync filter file.
