### ISSUE TITLE
the rsnapshot command line combine not correct when use SSH

### ISSUE THREAD

**Issue by jiming** [rsnapshot/rsnapshot#178]
/usr/bin/rsync -a --delete --numeric-ids --relative --delete-excluded 
--rsh=/usr/bin/ssh -i /root/.ssh/id_rsa 
--link-dest=/var/cache/rsnapshot/hourly.1/remote_2/ 
jiming@192.168.33.12:/home/jiming 
/var/cache/rsnapshot/hourly.0/remote_2/

should be

/usr/bin/rsync -a --delete --numeric-ids --relative --delete-excluded 
--rsh='/usr/bin/ssh -i /root/.ssh/id_rsa' 
--link-dest=/var/cache/rsnapshot/hourly.1/remote_2/ 
jiming@192.168.33.12:/home/jiming 
/var/cache/rsnapshot/hourly.0/remote_2/

The --rsh line need to be quoted

**Comment by StefanMoch** [comment]
@jiming 

Have you added `--rsh=/usr/bin/ssh -i /root/.ssh/id_rsa` via `rsync_long_args`?

You may try adding ` -i /root/.ssh/id_rsa` to `ssh_args` instead.

**Comment by jiming** [comment]
Thank you !
