### ISSUE TITLE
do rotation only, if maximum previous level exists [patch] 

### ISSUE THREAD

**Issue by Marwe** [rsnapshot/rsnapshot#18]
I created a feature request a whila ago on 
http://sourceforge.net/p/rsnapshot/feature-requests/30/

Since sourceforge seems to be dead or at least taken over by criminals [1], I repeat it here and add the patch file.
Hi,
here I have a simple patch that prevents rotation in a level, if there is nothing to roll into it from the lower level (e.g. no daily.{max} -> do not rotate weekly to prevent disappearing weekly.0).
Until now rotation is always done, and leads to holes in the backup scheme (e.g. weekly.[013] exist,weekly.[2] missing due to forced rotation).
This can then later lead to holes in the next levels (e.g. monthly.0 missing, if weekly.3 missing during monthly rotation), too.

I regard this as bug and the attached patch is quite simple.
Somebody should check and decide,
a) if there should be an option for the old behaviour (the 'dumb'/forced rotate).
b) if there are any problems with just bailing out then (I dont think so, but there are some options checked in the following parts).

Thanks for looking into it,
Martin

[1] http://www.gluster.org/2013/08/how-far-the-once-mighty-sourceforge-has-fallen/

**Comment by nkadel-skyhook** [comment]
Looks like the code got merged. Close this one?

**Comment by Marwe** [comment]
Thanks for the great work, further discussions, additions and merges. closing.
