### ISSUE TITLE
Backing up multiple remote servers #question

### ISSUE THREAD

**Issue by websafe** [rsnapshot/rsnapshot#181]
Hello,

I want to setup a single machine for backing up multiple remote servers.
Should I use a single rsnapshot.conf  file for each remote (source) server,
or is i t OK to use one single file and add multiple `backup` lines?

Any pros/cons?

**Comment by cebe** [comment]
if they have the same backup intervals(hourly, daily, ...), use one config, if they have different intervals, you need different configs.

**Comment by sam-at-github** [comment]
Mailing list: https://lists.sourceforge.net/lists/listinfo/rsnapshot-discuss
