### ISSUE TITLE
add option to ignore "source dir doesn't exist" error or run the check after the preexec command

### ISSUE THREAD

**Issue by b1362216** [rsnapshot/rsnapshot#183]
in some cases it's perfectly reasonable, that the source directory doesnt exist at the moment it is checked by rsnapshot. so an option to ignore it and/or an option to check the existence of the directory after the preexec hook would be nice.
current behaviour:
I create a read-only btrfs snapshot of the root directory in my preexec hook. Now I try to backup the directory with rsnapshot. I get: `ERROR: backup /mnt/btrfs_snaps/temp_rsnap_root root/ - Source directory \ "/mnt/btrfs_snaps/temp_rsnap_root" doesn't exist.`
expected behaviour:
I create a read-only btrfs snapshot of the root directory in my preexec hook. Now I try to backup the directory with rsnapshot. The content of my directory gets backed up.

**Comment by bemeyert** [comment]
I hit a similar issue. The preexec makes a DB dump and creates the configured file. But rsnapshot won't even run, because of the above behavior.

**Comment by sam-at-github** [comment]
I think the obvious solution is not to create the btrfs snapshot of the root directory in the preexec hook. Do it outside rsnapshot and wrap your call to rnsnapshot. Inevitably there are cases where the user will need to do this. Trying to handle every single setup scenario within rsnapshot won't lead anywhere good.

For reference:

> cmd_preexec:
>   Full path (plus any arguments) to preexec script (optional).  This script will run immediately before  each backup operation (but not any rotations). If the execution fails, rsnapshot will stop immediately.

Note the preexec is supposed to run before *every* `backup` line and root `snapshot_root` is a per invocation option. There is no pre-all-backing-up hook because it is expected and reasonable to expect that be done outside of rsnapshot, where as getting in between separate calls to backup lines can't be handled like that.

I have relative simple local backup that mounts/unmounts an encrypted removable drive, so I wrap rsnapshot like this:

    #!/bin/bash
    cd $(dirname "$(readlink -f $0)")

    function fail() {
      echo "$@"; exit 1;
    }

    function post() {
      ./backups-post || fail "Post failed"
    }

    cd `dirname $0`
    trap "post" EXIT
    ./backups-pre || fail "Pre failed. Will not continue"
    [[ -d /backups ]] || fail "Backup desination does not exist. Will not create it"
    rsnapshot -c /etc/backups-rsnapshot/backups-rsnapshot.conf sync && rsnapshot -c /etc/backups-rsnapshot/backups-rsnapshot.conf level0

**Comment by sam-at-github** [comment]
Sorry reopened. Reconsidering what the correct behavior should be and whether it should be an option or just always like the OP expects.

**Comment by bemeyert** [comment]
Hmm, I have two `backup` statements and the preexec command runs only once:
```
$ docker exec -t dev_kdp_backup_1 rsnapshot -c /rsnapshot.conf -v daily
echo 37 > /var/run/rsnapshot.pid
/db-backup.sh
/bin/cp -al /backup/shop/daily.0 /backup/shop/daily.1
/usr/bin/rsync -a --delete --numeric-ids --relative --delete-excluded \
    /data/ /backup/shop/daily.0/./
/usr/bin/rsync -a --delete --numeric-ids --relative --delete-excluded \
    /shop_db.sql.xz /backup/shop/daily.0/./
touch /backup/shop/daily.0/
rm -f /var/run/rsnapshot.pid
```
Version is 1.4.2 from Alpine and the corresponding configuration is:
```
$ docker exec -t dev_kdp_backup_1 egrep 'preexec|^backup' /rsnapshot.conf
cmd_preexec     /db-backup.sh
backup  /data/                  ./
backup   /shop_db.sql.xz    ./
```
On the other hand, I can understand your reasoning. rsnapshot should not try "do it all". Such stuff should be done with a wrapper script like you have posted.

**Comment by sam-at-github** [comment]
Oh yeah, your right it only runs once per invocation. I forgot about how this option works :/ Actually, there are a few other ~bug reports about preexec. In general people (including me and the OP) don't know when it runs in the scheme of things and that cause problems. In the other cases the suggested work around has always been as above - wrap calls to rsnapshot.

I don't think an option is a good idea. People will want to a more options for doing preexec at other stages. But IMO the more correct behavior for rsnapshot is to do the preexec before checking whether source dir existence. Checking the src dir exists is arguably "part of the backup operation" the preexec is supposed to be pre. Can't think of a good reason why it shouldn't be that way. The main risk for breakage of existing deploys is a preexec script that didn't used to get hit, gets hit with a src dir not existing, doesn't account for that and fails. If preexec script just fails rsnapshot aborts which it would do if src dir check had been done first anyway. But the script could fail in some perverse way - unlikely.

**Comment by bemeyert** [comment]
It would make sense (in any way) to execute the preexec before checking the source dirs existence.
