### ISSUE TITLE
Ability to specify copy arguments.

### ISSUE THREAD

**Issue by JamesColeman-SH** [rsnapshot/rsnapshot#184]
It would be neat if you could specify the arguments used for the cp command during the directory clone. With BTRFS, you can create light weight copies with `--reflink=always` which will be better than using hard links. So instead of using `cp -al`, I would prefer to use `cp -a --reflink=always` on BTRFS systems.

**Comment by StefanMoch** [comment]
@JamesColeman-SH 

See the `cmd_cp` option: you may replace cp with a script, which ignores the `-al` option and calls `cp -a --reflink=always`, though be aware that with the `link_dest` option, cp is not used.

There is also [a patch for rsync, implementing --reflink](https://bugzilla.samba.org/show_bug.cgi?id=10170).

Using reflinks where available is a good idea, as it is more flexible than hardlinks: different inodes with the same data (but copy on write), allows for different metadata, so data sharing is possible with metadata changes.

File systems with support for reflinks, from a quick search: BTRFS, OCFS2, XFS and NFS.

This is also somewhat related to #201, where possibly an replacement for hardlinks is needed.
