### ISSUE TITLE
"WARNING: The verbosity-level is "3" despite subsequent declaration at line 111."

### ISSUE THREAD

**Issue by ChristopherW** [rsnapshot/rsnapshot#185]
rsnapshot 1.4.2 on CentOS 7 Core (installed via yum) throws an error when I run rsnapshot -t hourly (or any of them) -- seems the log level isn't being accepted.

rsnapshot.conf has `verbose 4` and `loglevel 4` (I can't get 5 to work due to a "require Lchown / LChown module not found" error which I've not had time to fully fix, despite trying to install Lchown).

The default verbosity of 3 is overriding my specified verbosity, despite me declaring it in the config and `rsnapshot configtest` returning an OK.

I think this may also be causing a subsequent problem with rsnapreport returning a `NO STATS DATA` message in my email reports.

**Comment by sandrotosi** [comment]
i have the exact same issue with snapshot 1.4.2 on Debian

**Comment by sandrotosi** [comment]
it appears to be because i passed `-v` on the command-line, which maps to verbose 3, while setting verbose=4 in the config file; setting `-V` (which maps to verbose 4) the error went away

that was pretty unintuitive

**Comment by ruedigerkupper** [comment]
Isn't it usual Linux behavior that options set on the command line override settings in config files?

**Comment by sandrotosi** [comment]
it is, but that should not generate a warning.

**Comment by sgpinkus** [comment]
Thanks for the report. The warning is good. It only arises if you specify higher verbosity in config than you did on command line and isn't going to hurt anyone.

**Comment by DrHyde** [comment]
And to install `Lchown` ...

`$(head -1 $(which rsnapshot)|sed 's/^..//') -MCPAN -e 'install qw(Lchown)'`

**Comment by sandrotosi** [comment]
> Thanks for the report. The warning is good. It only arises if you specify higher verbosity in config than you did on command line and isn't going to hurt anyone.

the warning is *not* good: if i decided to override the configuration with a command-line switch, there's no reason to emit a warning; no other commonly-used linux tools does that.

**Comment by ruedigerkupper** [comment]
Well, it is confusing and unusual to have warnings when overriding config options on the command line. The user should no what they do when they specify an option on the command line.

**Comment by DrHyde** [comment]
The typical use case of rsnapshot is not to invoke it from the command line though, it's to invoke it from a cron job, controlled with a configuration file. If the user is running it manually and over-riding the config file I don't have a problem with them getting warnings.
