### ISSUE TITLE
Change cache settings

### ISSUE THREAD

**Issue by gidoBOSSftw5731** [rsnapshot/rsnapshot#192]
So I'm trying to backup my whole PC with rsnapshot to a local rsync server but I have a issue, rnsapshot is trying to cache my WHOLE system (900GB) on my pc which has about 40gb left... can I limit/disable caching?

[NOTE: askrd here but no info: https://askubuntu.com/questions/938114/how-to-use-rsnapshot-with-limited-no-cache ]

**Comment by bebehei** [comment]
Checkout the `sync_first`-setting. There is no option to specify the cache size at all.

`sync_first` stores a 2nd copy of your current files on your `backup_root`. Only after successful sync, it will rotate. Disabling this behavior will save space, but it will likely result in a broken backup.

Also please use the [mailing-list](https://lists.sourceforge.net/lists/listinfo/rsnapshot-discuss) for future questions.

**Comment by gidoBOSSftw5731** [comment]
Do you mean snapshot_root? there is no backup_root...

**Comment by bebehei** [comment]
Shame on me. Yes, of course it's `snapshot_root`.

**Comment by gidoBOSSftw5731** [comment]
so is there a way to like just disable caching? why cant it just copy straight from disk?
