### ISSUE TITLE
post_exec runs before sync_first finishes syncing sync directory to the rotation.

### ISSUE THREAD

**Issue by Zerophase** [rsnapshot/rsnapshot#194]
post_exec scripts run after the sync finishes, but not after rsnapshot finishes running when sync_first is enabled. Feels like scripts for mirroring the directory structure to a second disk should run after the entire rotation in this case. Maybe, there needs to be a post_sync and post_exec for handling different timings for when to run scripts.

**Comment by sam-at-github** [comment]
> post_exec scripts run after the sync finishes, but not after rsnapshot finishes running when sync_first is enabled

That is the intended behavior.

> Feels like scripts for mirroring the directory structure to a second disk should run after the entire 
rotation in this case.

If your using `sync_first`, sync and rotation happen in two different invocations of rsnapshot. I don't see a problem with using `cmd_postexec` to "mirror the directory structure to a second disk". If you really insist on doing it after rotation (for some weird reason) `rsnapshot sync && rsnapshot alpha && mirror`.

> Maybe, there needs to be a post_sync and post_exec for handling different timings for when to run scripts.

`cmd_postexec` *is* post sync

**Comment by Zerophase** [comment]
It's since other wise you're backing up the rsnapshot directory structure with a fresh `.sync` directory every time. My understanding of what's going on is for the hourly snapshots you'd have to copy over more with the '.sync' directory each time with rsync than waiting for the rotation finish before backing up the rsnapshot backup to another location.

**Comment by sam-at-github** [comment]
> It's since other wise you're backing up the rsnapshot directory structure with a fresh .sync directory every time. 

I gathered you intention was to sync your entire rsnapshot_root. I'm not sure what you are doing exactly, but I'm sure it can be achieved with scripting wrappers around rsnapshot easily.

**Comment by Zerophase** [comment]
It's syncing the entire rsnapshot_root. I just thought having the '.sync' folder in there which disappears after every rotation leads to future 'rsync' runs taking longer than needed.

**Comment by sam-at-github** [comment]
I doesn't disappear. Think of .sync as your most recent backup. When you do a rotation it takes a snapshot of that. Next time you do a sync the latest rotation is unaffected.

**Comment by Zerophase** [comment]
Must just be the directory size that's making rsync take forever to test which file parts have changed.
