### ISSUE TITLE
man page looks funny

### ISSUE THREAD

**Issue by jayenashar** [rsnapshot/rsnapshot#197]
https://github.com/rsnapshot/rsnapshot/blob/717d75adc1b92cb413bbcfdf3ec4ee860acbae4d/rsnapshot-program.pl#L7213

appears like this for me:

```
               backup_exec      ssh root@1.2.3.4 "du -sh /.offsite_backup"
               optional/ backup_exec      rsync -az /.snapshots/daily.0
               root@1.2.3.4:/.offsite_backup/   required/ backup_exec
               /bin/true/
```

1) word wraps are lost
2) `/` appears at the end of the line

**Comment by sam-at-github** [comment]
Fixed in master. Thanks!
