### ISSUE TITLE
optional backups

### ISSUE THREAD

**Issue by jayenashar** [rsnapshot/rsnapshot#198]
i see `backup_exec` has an `optional` option.  can this be added for `backup`?

my use case is that i backup a laptop which is often asleep, but rsnapshot is running on my server.  i can use a pre script to check when the backup should run, but i don't know how to best use `backup_script` or `backup_exec` for this.  i still need the hard links to be preserved between snapshots.

**Comment by sgpinkus** [comment]
This won't ever get don't. Don't the use case for optional backups is a strong one. "Optional" script just means ignore the return value. You hardly ever want to ignore a failed backup. Cheers.

**Comment by jayenashar** [comment]
i'm backing up a laptop which is off half the time.  so i've got a wrapper script to ignore a specific error `rsync returned 255` for that laptop only.

**Comment by sgpinkus** [comment]
Oh I see. I would just use a separate config for that.

**Comment by jayenashar** [comment]
thanks!  i didn't think of that
