### ISSUE TITLE
Running different tiers concurrently

### ISSUE THREAD

**Issue by bastibe** [rsnapshot/rsnapshot#200]
If several backups are scheduled while my computer is turned off, they will all be run concurrently when the computer wakes up. In my case, every morning my hourly and daily backups are triggered the moment my computer wakes up. 

I could use a lock file to prevent concurrent execution, but then my daily backup might not trigger. So instead, I have disabled the lock file. So far, this seemed not to have caused any issues.

Is it a problem to run different backup tiers concurrently? Am I risking my data?

**Comment by StefanMoch** [comment]
@bastibe 
This should not be a problem as hourly and daily are rotated independently and the rotation just renames directories and does not touch the files in the directories. This should not risk your data, though regular checks are advisable nevertheless.

The worst case is probably a temporarily missing `daily.0`, if `hourly.last` was just removed when it was about to be renamed to `daily.0`. A temporarily missing `hourly.last` can be happen during normal operation: when daily renamed it to `daily.0`.

To keep everything “in order” (as far as this is useful if not every hourly is run anyway), you may consider doing 23 times a day (if you would normally do 24) `rsnapshot sync && rsnapshot hourly` and one time a day `rsnapshot daily; rsnapshot sync && rsnapshot hourly`.

**Comment by bastibe** [comment]
I didn't know about `rsnapshot sync`. Thank you!
