### ISSUE TITLE
macOS & APFS

### ISSUE THREAD

**Issue by orbsmiv** [rsnapshot/rsnapshot#201]
Not so much a bug report than an observation but presumably rsnapshot won't work on macOS with the APFS filesystem, given that Apple's new filesystem doesn't support hard links?

**Comment by StefanMoch** [comment]
@orbsmiv 
Without hard links it will not work as expected. It can probably be made to work fairly easily with the right options to `cp` or `rsync` (should the hard linking options even fail) – at the risk of losing the space savings doing real copies of unchanged files.

The [FAQ](https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/APFS_Guide/FAQ/FAQ.html) does not mention file hard links (which are used by rsnapshot), only directory hard links, which are not used by rsnapshot. So it is still unclear to me, if file hard links on APFS are supported or not.

If the `clones` in APFS are supported by `cp` or `rsync`, this may be used as replacement for hard links with the right options to these tools.

It may also be possible to use APFS's snapshot feature in a similar way LVM snapshots can be used.

**Comment by StefanMoch** [comment]
Just checked: rsync options are configurable, the `-al` to cp is hardcoded, though `cmd_cp` may be changed. IIRC, cp is not used when using `link_dest`.

**Comment by gagarine** [comment]
On APFS shouldn't we simply duplicate the files? APFS is supposed to have instant copy and not taking more space for copy of the same file.

**Comment by mlbarrow** [comment]
Huh? APFS **does** have hardlinks; it doesn't have hardlinks on directories (like many other filesystems, excluding HFS+).

```
/dev/disk2s1 on / (apfs, local, journaled)
~: touch this
~: ln this that
~: ls -li this that
7071043 -rw-r--r--  2 mlbarrow  staff  0 Aug  5 20:41 that
7071043 -rw-r--r--  2 mlbarrow  staff  0 Aug  5 20:41 this
```

**Comment by dmd** [comment]
APFS supports file hardlinks - just like most other filesystems.

APFS does not support directory hardlinks - just like most other filesystems.

There is nothing to see here. This issue should be closed.

**Comment by DrHyde** [comment]
Indeed. The only slightly weird thing about APFS is that it is, by default, case-insensitive. But again, that's no different from HFS+.
