### ISSUE TITLE
Wish: Shorten path in backup

### ISSUE THREAD

**Issue by heini** [rsnapshot/rsnapshot#202]
Hi,

when backing up directories buried deep inside the directory tree, I don't always need the complete path to be replicated in the backup. Would be nice to either optionally specify a shorter path or have an option to keep the basename only, so either
`backup  /some/very/very/long/path data/ path`
or
`backup  /some/very/very/long/path data/ use_basename=1`
which would then result in something like
`.../hourly.0/data/path`
instead of
`.../hourly.0/data/some/very/very/long/path`

**Comment by bebehei** [comment]
Search the manpage for `relative`. There's everything explained about how to use `--relative`. That's exactly what you want.

**Comment by heini** [comment]
Ah, sorry. Checked the docs before, but must have missed this somehow. However, the man page only talks about *adding* options using 
> +rsync_long_args=...

but --relative is in the defaults already, so I'd rather need to remove it. Is
> -rsync_long_args=...

possible, too?

**Comment by bebehei** [comment]
If you've got questions and/or have to solve common problems, it might be the best to ask there: https://lists.sourceforge.net/lists/listinfo/rsnapshot-discuss
