### ISSUE TITLE
rsync version 3.1.3 breaks rsnapreport.pl

### ISSUE THREAD

**Issue by dimm0k** [rsnapshot/rsnapshot#207]
Currently using Slackware64 13.37, a bit of an old version, and everything was fine with rsnapshot and rsnapreport.pl with rsync version 3.0.8 until recently when I updated to version 3.1.3 made available from Slackware. backups still work fine however the reports e-mailed to me from rsnapreport.pl all give totals of either N/A or 0. the logs show nothing unusual either...

**Comment by StefanMoch** [comment]
Hello @dimm0k,

this issue is probably the same as #128. The fix (79e25dc83bc2) is already in the master branch, however not yet in a released version.

**Comment by sam-at-github** [comment]
Yep probably time someone got around to doing v1.5.0 release.
