### ISSUE TITLE
"ssh_args" does not work due to lack of quoting

### ISSUE THREAD

**Issue by mmalmeida** [rsnapshot/rsnapshot#208]
I am running 1.4.2 and hit the same problem described in #89 
This is caused by the fix in #15 

However, a configuration with:
```
rsync_short_args        -azPv
rsync_long_args --delete --numeric-ids --relative --delete-excluded --timeout=900 --inplace
#backups
backup  root@8.8.8.8:/    pc_8   include_file=/my/include/file,ssh_args=-p 22
```

will produce (via rsnapshot -t daily):
`/opt/bin/rsync -azPv --delete --numeric-ids --relative --delete-excluded \
    --timeout=900 --inplace \
    --include-from=/my/include/file \
    --rsh=/usr/bin/ssh -p 22 \
    --link-dest=/share/backup/daily.1/pc_8 root@8.8.8.8:/ \
    /share/backup/daily.0/pc_8 
`

Note the --rsh option, that should read -e "/usr/bin/ssh -p 22" but doesn't quote the port (which, like the OP in #89 mentions, treats the -p as an rsync parameter, and not an ssh parameter.

Note: Opening similar ticket since the previous one requested a configuration that would cause this.

**Comment by sam-at-github** [comment]
I think you need qoutes in the ssh_args per-backup-point option:

    backup	root@8.8.8.8:/	pc_8   include_file=/my/include/file,ssh_args="-p 22"

**Comment by sam-at-github** [comment]
Update: Sorry, I don't think the quotes matter. However, are you sure this is actually the problem. What is printed in `-t` mode is misleading and not consistent with the command that is actually run. Pretty sure that _will_ be quoted. I just test and works for me.

**Comment by mmalmeida** [comment]
Hi @sam-at-github . Is there a ticket to fix the -t command then?
I think it is confusing if the command to show what will be run does not show what will be run accurately...
