### ISSUE TITLE
Feature: 'mv last first' instead of 'rm last' & 'cp first second'

### ISSUE THREAD

**Issue by ravethetadpole** [rsnapshot/rsnapshot#213]
In my usage, the total archive is much much bigger than the typical deltas. This has resulted in some very long backups. Looking in the log, most of this time is spent on 'rm hourly.5' (12 minutes) and 'cp -al hourly.0 hourly.1' (18 minutes). The actual rsync isn't all that long (18 minutes).

An alternative would be to 'mv hourly.5 hourly.0'. I.e. using hourly.5 as the starting point for the sync to hourly.0, instead of using hourly.1 as the starting point. It avoids both the 'rm' and the 'cp'. The downside is that it would require sending all the changes since hourly.5, which would include changes you had already synced previously. Which is why this would have to be an optional flag, defaulting off. Those with large deltas or with network limitations would want it off. Those with small deltas would want it on.

Has this been considered? Is there a way to achieve this with the current implementation? Perl is incomprehensible to me.

[A stack exchange question I attempted on the subject](https://unix.stackexchange.com/questions/457483)

**Comment by sam-at-github** [comment]
No I don't think it has been considered. So you are proposing to change the way hourly backups are retained, from a FIFO to effectively a circular buffer. The rationale for this is that the "queue" shift operation (rm) takes along time.

You state the rm hourly.5 takes 12 minutes, and the rsync takes 18 minutes. But how much long does the rsync take if you sync onto a staler base? It's definitely going to take longer. I think in the (vast?) majority of cases this won't result in better performance.

Note you might want to look at `use_lazy_deletes` and `link_dest` option. I'm not sure if `link_dest` will result in much better perf than `cp -al`, never had a reason to use it. But maybe worth testing.

**Comment by ravethetadpole** [comment]
You correctly interpreted my suggestion: circular buffer.

I haven't attempted doing a manual rsync onto a staler base. I strongly suspect that it won't be much different from the fresh base. One of my uses, as an example, is backing up many years of daily log files. The number of new files is tiny compared to the number of old files. I get the impression that our drive array isn't the fastest either, so the metadata work that rsync has to do is slow. I'm doubting there are stats on the typical use case of rsnapshot; my guess would be that most uses are dominated by unchanging data.

I've now tried `use_lazy_deletes` and `link_dest`. I hadn't used them before, because their descriptions didn't sound useful.

`link_dest` has improved things. It avoids the `cp -al` step entirely, and the rsync step doesn't take longer at all. I guess it's the same metadata work either way. So I'm leaving `link_dest` on. It reduces my problem.

`use_lazy_deletes` is less exciting. It moves the rm to the end of the process, but it still has to do the same amount of work. However, when combined with `link_dest` at least, it does mysteriously make the `rm` go faster: 7 minutes instead of 12 minutes. Maybe the cache is hot because the `link_dest` rsync has just finished? I guess I'll leave it on too.

Reading the rsync documentation, I have an improvement to my idea: use the circular buffer to `mv <last> <first>` combined with `rsync --link_dest <second> <source> <first>`. That avoids the `rm` step, and still avoids copying large files from the source, getting them from `<second>`, just like the `link_dest` option does. Best of both worlds? I don't see any downsides to that. Do you?

**Comment by ravethetadpole** [comment]
I tested my theory of circular buffer + `--link_dest <second>` by putting together a bash script that recreates what I think rsnapshot ought to do, and running that instead of rsnapshot for a smallest increment run. It definitely went faster, and I think did everything correctly. It took just 15 minutes for the `rsync`. The next automatic run (with `link_dest` and `use_lazy_deletes`) took 15 minute for the `rsync` and 7 minutes for the `rm`. So it runs the sync in the same time, but avoids the deletion step entirely.

So I think I have a good idea here. How do I reach the right audience of experts who can shoot down my idea before any more time is invested into it -- or can start thinking about how this can be incorporated?

Here is the script that I put together. The key features are the `circular_rollover` moving of directories, and the `link_dest` to `daily.1` in the rsync. No `rm` and no `cp -al` needed.

```
#! /bin/bash

set -v

date

echo $$ > /var/run/rsnapshot.pid

mv /mnt/NFSDATA/.snapshot/daily.6/ /mnt/NFSDATA/.snapshot/circular_rollover
mv /mnt/NFSDATA/.snapshot/daily.5/ /mnt/NFSDATA/.snapshot/daily.6/
mv /mnt/NFSDATA/.snapshot/daily.4/ /mnt/NFSDATA/.snapshot/daily.5/
mv /mnt/NFSDATA/.snapshot/daily.3/ /mnt/NFSDATA/.snapshot/daily.4/
mv /mnt/NFSDATA/.snapshot/daily.2/ /mnt/NFSDATA/.snapshot/daily.3/
mv /mnt/NFSDATA/.snapshot/daily.1/ /mnt/NFSDATA/.snapshot/daily.2/
mv /mnt/NFSDATA/.snapshot/daily.0/ /mnt/NFSDATA/.snapshot/daily.1/
mv /mnt/NFSDATA/.snapshot/circular_rollover/ /mnt/NFSDATA/.snapshot/daily.0

date

/usr/bin/rsync -a --delete --numeric-ids --relative --delete-excluded --exclude=core.[0-9]* --rsh=/usr/bin/ssh --link-dest=/mnt/NFSDATA/.snapshot/daily.1/${MY_HOST}/ root@${MY_HOST}:/home/${MY_USER_NAME} /mnt/NFSDATA/.snapshot/daily.0/${MY_HOST}/

# ... more paths to backup appear here...

touch /mnt/NFSDATA/.snapshot/daily.0/

rm -f /var/run/rsnapshot.pid

date
```

**Comment by ravethetadpole** [comment]
Hmm. To me this is free performance for larger backups. But maybe performance isn't on the radar of the maintainers. It uses the same mv/rsync commands that rsnapshot already uses, so I think is low risk. But nothing is zero risk.

If it has a low probability of being merged, I'm less likely to do the work. Which, of course, is why I was asking before trying to do the work, so I appreciate being told now. Perl is already outside my experience, so it was going to be challenging, and I worry about the quality of what I can produce, which just makes the chances of it being integrated worse. And who wants to write tests!?

If I end up doing something, I'll let the mailing list know. If I think I've done something worthwhile, I may make a PR. More likely is that I'll use my bash script instead of the daily interval of rsnapshot.

**Comment by judouk** [comment]
I read this with interest - and as my backups are on slow SATA disks, I have adopted this for my hourlies.
I have 24 hourly snapshots and the rm/cp tasks were taking (in some cases) close to 35 minutes to complete. The hourly rsync pulled around 300 files and completed in less than a few minutes.

I ran into a few issues when first doing this - and I have to rsync the same files 24 times each day....but the whole process now finishes in around 6 minutes

Its certainly an option that I'd make use of in rsnapshot

**Comment by jiamliang** [comment]
@ravethetadpole have you used your bash script in your production enviroment ?
in my case,  I need 5~6 hours in doing rm & cp .  :(

**Comment by jbonyun** [comment]
I had to go look because it has been a while. I opted to stick with the stock rsnapshot, including the `use_lazy_deletes` and `link_dest` options. It was good enough for my case.

But I still believe my script is an improvement. If you have a 5-6 hour problem, I'd suggest that you give it a try. Unfortunately I can't claim that it has been production-tested.

Maybe @judouk has used it in production on a regular basis and could speak to its stability?

**Comment by judouk** [comment]
I actually stopped using the script - but by complete accident.
Had it not been for this thread, I wouldnt have realised until I next had a performance issue :)

Going back through my emails, I see that the hourly snapshots were taking some time...especially during the night but most were completing in around 45 minutes
Mon, 21 Oct 2019 01:24:08 +0100
Mon, 21 Oct 2019 03:16:25 +0100
Mon, 21 Oct 2019 04:48:21 +0100
Mon, 21 Oct 2019 05:45:57 +0100
Mon, 21 Oct 2019 06:42:31 +0100
Mon, 21 Oct 2019 07:48:11 +0100
Mon, 21 Oct 2019 08:45:37 +0100
Mon, 21 Oct 2019 09:27:17 +0100
Mon, 21 Oct 2019 10:19:10 +0100
Mon, 21 Oct 2019 11:23:53 +0100
Mon, 21 Oct 2019 13:28:36 +0100
Mon, 21 Oct 2019 14:27:14 +0100
Mon, 21 Oct 2019 15:38:37 +0100

I had to make some changes to the script but have put this back into production.
The big problem is that each backup cycle uses more and more bandwidth but I recall that the process completed far quicker and therefore had less impact to my SATA drives.
I'll post some timings over the coming days

**Comment by jiamliang** [comment]
Thanks @jbonyun, I will try it in my case.
Thanks @judouk .

**Comment by judouk** [comment]
If you are planning to use this in production, I thought I'd share my script with you.
I only use this for the hourly snapshots at present as daily/weekly/monthly are already just simple renames with deletes.

You may need to adjust this slightly based on your requirements

`#!/bin/bash

if [ $# -lt 1 ]; then
  echo "No option specified"
  exit
fi

if [ ! -e $1 ]; then
  echo "Unable to find file $1"
  exit
fi


# So, assuming that everything is as we expect
RSYNCLONG=$(grep rsync_long_args $1 | sed -e 's/^rsync_long_args//' -e 's/^[[:space:]]//')
SSHARGS=$(grep ssh_args $1 | sed -e 's/^ssh_args//' -e 's/^[[:space:]]//')
LOCKFILE=$(grep lockfile $1 | sed -e 's/^lockfile//' -e 's/^[[:space:]]//')
ROOT=$(grep snapshot_root $1 | sed -e 's/^snapshot_root//' -e 's/^[[:space:]]//')

echo $$ > ${LOCKFILE}

cd $ROOT
mv hourly.23 hourly.keep
for m in 22 21 20 19 18 17 16 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1 0; do
  C=$(( m + 1 ))
  mv hourly.$m hourly.$C
done
mv hourly.keep hourly.0

# When the daily snapshot runs, it renames hourly.23 ... so after the rename, there is nothing to base my first image on
if [ ! -e hourly.0 ]; then
  cp -al hourly.1 hourly.0
fi

echo "#!/bin/bash" > ${LOCKFILE}.run
echo "set -x" >> ${LOCKFILE}.run

while read line; do
  BACKUP=$(echo $line | awk '{print $1}')
  EXCLUDE=""
  if [ "$BACKUP" == "backup" ]; then
    OPT2=$(echo $line | awk '{print $2}')
    OPT3=$(echo $line | awk '{print $3}')
    OPT4=$(echo $line | awk '{print $4}')
    if [ "$OPT4" != "" ]; then
      # Need to split out exclude lines into options
      EXCLUDE=$(echo $OPT4 | tr ',' ' ' | sed -e 's/exclude=/--exclude=/g')
    fi
    echo echo /opt/bin/rsync -av $RSYNCLONG $EXCLUDE -e \"/usr/bin/ssh $SSHARGS\" $OPT2 $ROOT/hourly.0/$OPT3 >> ${LOCKFILE}.run
    echo /opt/bin/rsync -av $RSYNCLONG $EXCLUDE -e \"/usr/bin/ssh $SSHARGS\" $OPT2 $ROOT/hourly.0/$OPT3 >> ${LOCKFILE}.run
  fi
done < $1

chmod 700 ${LOCKFILE}.run
${LOCKFILE}.run > ${LOCKFILE}.output

touch hourly.0

cat ${LOCKFILE}.output | /usr/local/scripts/rsnapreport.pl

rm ${LOCKFILE} ${LOCKFILE}.run ${LOCKFILE}.output`

**Comment by jiamliang** [comment]
@judouk  Thanks a lot!

**Comment by judouk** [comment]
As promised, some figures for the past few days. As expected, the 'daily' snapshot takes longer than the others but, overall, this script performs very well so I plan to keep it running.


Sun, 27 Oct 2019 00:10:43 +0100
Sun, 27 Oct 2019 01:06:18 +0100
Sun, 27 Oct 2019 02:10:27 +0000
Sun, 27 Oct 2019 03:42:02 +0000
Sun, 27 Oct 2019 04:10:53 +0000
Sun, 27 Oct 2019 05:22:58 +0000
Sun, 27 Oct 2019 06:18:22 +0000
Sun, 27 Oct 2019 07:08:56 +0000
Sun, 27 Oct 2019 08:06:46 +0000
Sun, 27 Oct 2019 09:06:28 +0000
Sun, 27 Oct 2019 10:07:30 +0000
Sun, 27 Oct 2019 10:37:14 +0000
Sun, 27 Oct 2019 11:07:23 +0000
Sun, 27 Oct 2019 12:07:06 +0000
Sun, 27 Oct 2019 13:06:13 +0000
Sun, 27 Oct 2019 14:06:34 +0000
Sun, 27 Oct 2019 15:07:27 +0000
Sun, 27 Oct 2019 16:06:20 +0000
Sun, 27 Oct 2019 17:08:19 +0000
Sun, 27 Oct 2019 18:36:20 +0000
Sun, 27 Oct 2019 19:09:31 +0000
Sun, 27 Oct 2019 20:06:30 +0000
Sun, 27 Oct 2019 21:07:27 +0000
Sun, 27 Oct 2019 22:08:06 +0000
Sun, 27 Oct 2019 23:06:12 +0000
Mon, 28 Oct 2019 00:19:26 +0000
Mon, 28 Oct 2019 01:06:08 +0000
Mon, 28 Oct 2019 02:11:32 +0000
Mon, 28 Oct 2019 03:24:59 +0000
Mon, 28 Oct 2019 04:10:52 +0000
Mon, 28 Oct 2019 05:16:31 +0000
Mon, 28 Oct 2019 06:11:41 +0000
Mon, 28 Oct 2019 07:11:30 +0000
Mon, 28 Oct 2019 08:10:31 +0000
Mon, 28 Oct 2019 09:09:55 +0000
Mon, 28 Oct 2019 10:11:21 +0000
Mon, 28 Oct 2019 11:10:26 +0000
Mon, 28 Oct 2019 12:10:50 +0000
Mon, 28 Oct 2019 13:09:40 +0000
Mon, 28 Oct 2019 14:14:25 +0000
Mon, 28 Oct 2019 15:11:22 +0000
Mon, 28 Oct 2019 16:09:15 +0000
Mon, 28 Oct 2019 17:15:48 +0000
Mon, 28 Oct 2019 18:10:41 +0000
Mon, 28 Oct 2019 19:13:33 +0000
Mon, 28 Oct 2019 20:10:24 +0000
Mon, 28 Oct 2019 21:12:56 +0000
Mon, 28 Oct 2019 22:11:56 +0000
Mon, 28 Oct 2019 23:09:56 +0000

**Comment by jiamliang** [comment]
@judouk  Thanks for your reply.  i think, i need to have a try. thanks again.

**Comment by DrHyde** [comment]
syncing onto a staler base would end up using more disk space
