### ISSUE TITLE
There is no HOW-TO on the website

### ISSUE THREAD

**Issue by tchaffee** [rsnapshot/rsnapshot#218]
The README here and the website both talk about a HOW-TO guide that is on the website. I cannot find that anywhere on the website.

**Comment by kav2k** [comment]
Duplicate of https://github.com/rsnapshot/rsnapshot/issues/93
and to some extent https://github.com/rsnapshot/rsnapshot.github.io/issues/1

You can access the last state of HOWTO by downloading https://raw.githubusercontent.com/rsnapshot/rsnapshot/gh-pages/docs/HOWTOs/rsnapshot-HOWTO.en.html
