### ISSUE TITLE
rsnapshot bailing out on rsync error == 0, should continue, instead...

### ISSUE THREAD

**Issue by marcolino** [rsnapshot/rsnapshot#22]
When for some reason one backup fails (typically because that server is down...), the whole rsnapshot process dies, and all following snapshots are not executed...

I would suggest to change, in sub handle_rsync_error:

    if (0 == $retval) { bail('retval == 0 in handle_rsync_error() ('.$$bp_ref{'src'}.')'); }

with

    if (0 == $retval) {
        print_err ("$config_vars{'cmd_rsync'} error 0 on $$bp_ref{'src'} (check host is up and accepting ssh connections...)", 2);
        syslog_err("$config_vars{'cmd_rsync'} error 0 on $$bp_ref{'src'} (check host is up and accepting ssh connections...)");
      }

**Comment by bebehei** [comment]
@marcolino could you please verify it or close the bug-report?
