### ISSUE TITLE
chattr +i or chattr +a implementation

### ISSUE THREAD

**Issue by socomsystems** [rsnapshot/rsnapshot#221]
Not so much an issue, more of a question of where would be the best place code wise to implement the use of chattr +i or chattr +a on snapshot volumes once complete to lock those volumes down protecting them from being modified from possible malware infestations etc?

**Comment by StefanMoch** [comment]
@socomsystems: regarding `chattr +i` (or `+a`): this will also prevent hardlinking of the files flagged this way. `rsync --link-dest` will not make hardlinks for unchanged files, but instead copies them.

**Comment by socomsystems** [comment]
@StefanMoch I was considering scripting a bit more intelligence into the process, e.g. not just applying chattr but possibly doing it in such a way that hardlinking may still work.  Thank you for your input, I will definitely keep you posted.  Is there a cmd_preexec option as well?

**Comment by sam-at-github** [comment]
>  Is there a cmd_preexec option as well?

Yes. `man rsnapshot`.
