### ISSUE TITLE
I just found a possible typo in /usr/share/doc/rsnapshot/examples/rsnapshot.conf.default.gz

### ISSUE THREAD

**Issue by storyjesse** [rsnapshot/rsnapshot#225]
The default config file has the following example of usage on line 233
`#backup /foo/bar/       localhost/      one_fs=1, rsync_short_args=-urltvpog`
Assuming that `/foo/bar/` exists this line works despite there being a < space > between `one_fs=1, rsync_short_args`

However, if the rsync_short_args are ADDED using '+rsync_short-args' the following error is generated:
```
----------------------------------------------------------------------------
rsnapshot encountered an error! The program was invoked with these options:
/usr/bin/rsnapshot -tv monthly 
----------------------------------------------------------------------------
ERROR: /etc/rsnapshot.conf on line 233:
ERROR: backup /foo/bar/ localhost/ one_fs=1, +rsync_short_args=-urltvpog - \
         Syntax error on line 233 in extra opts: one_fs=1, \
         +rsync_short_args=-urltvpog 
ERROR: ---------------------------------------------------------------------
ERROR: Errors were found in /etc/rsnapshot.conf,
ERROR: rsnapshot can not continue. If you think an entry looks right, make
ERROR: sure you don't have spaces where only tabs should be.
```
Removing the < space > solves the issue and rsnaptshot runs, both with and without the ADDED '+' switch

P.S. I'm sorry I don't know how to submit a patch otherwise I would do so.

**Comment by sam-at-github** [comment]
Your right. Docs say per-backup-point options should be be comma separated (ideally we should be a bit more robust to that but meh). Pushed fix to doc. Thanks for reporting.
