### ISSUE TITLE
how to prevent syncing the previous backup after copying it with "cp --archive --link"

### ISSUE THREAD

**Issue by jerome-bouat** [rsnapshot/rsnapshot#226]
I noticed the below behaviour into my log :
`[2019-05-14T18:03:01] native_cp_al("/target/dossiers/daily.0", "/target/dossiers/daily.1")

[2019-05-14T20:38:05] /usr/bin/rsync -a --delete --numeric-ids /target/dossiers/daily.0/ /target/dossiers/daily.1/

[2019-05-14T21:04:16] /usr/bin/rsync -rltD --delete --numeric-ids --delete-excluded /source/dossiers/ /target/dossiers/daily.0/./ `
What for the first rsync after native_cp_al is ?
Could we skip this first rsync (quite 1 hour) ?

**Comment by djk20** [comment]
Jerome,

Could you please add some more details/context so we could more easily try to reproduce this?
For example, your version of rsnapshot, your rsnapshot.conf (minus comments is fine) and the command you (or cron) ran.

David Keegel.

**Comment by DrHyde** [comment]
From the comment immediately before native_cp_al's implementation:

```
# This is a purpose built, native perl replacement for GNU "cp -al".
# However, it is not quite as good. it does not copy "special" files:
# block, char, fifo, or sockets.
# Never the less, it does do regular files, directories, and symlinks
# which should be enough for 95% of the normal cases.
# If you absolutely have to have snapshots of FIFOs, etc, just get GNU
# cp on your system, and specify it in the config file.
#
# Please note that more recently, this subroutine is followed up by
# an rsync clean-up step. This combination effectively removes most of
# the limitations of this technique.
```

**Comment by jerome-bouat** [comment]
That's the point. I would appreciate an option which will prevent the "rsync clean-up" step. I know that there aren't any "special" files in my case. This extra "rsync" breaks my disk a little more without any added value in my case.

**Comment by davidcantrelluk2** [comment]
Given that rsnapshot isn't really being maintained any more the best solution would probably be to install GNU cp and configure rsnapshot to use that. If you let us know what platform you're using hopefully one of us can help you get that installed.

**Comment by jerome-bouat** [comment]
My host is M. Windows 7 x86_64. I'm using the rsnapshot package shipped with Cygwin x86_64.
Comments into the configuration file tell :
"""
\# LINUX USERS:   Be sure to uncomment "cmd_cp". This gives you extra features.
\# EVERYONE ELSE: Leave "cmd_cp" commented out for compatibility.
"""

Do you mean I can safely define the below variable :
"""
cmd_cp		/bin/cp
"""
?

**Comment by davidcantrelluk2** [comment]
Only if that's GNU cp. `cp --help` will tell you if it is.

**Comment by jerome-bouat** [comment]
My cygwin package provides GNU cp according to "cp --version".
I set the below value :
"""
cmd_cp /usr/bin/cp
"""
Thanks.
