### ISSUE TITLE
link to howto is broken

### ISSUE THREAD

**Issue by daniel-wtd** [rsnapshot/rsnapshot#228]
Hi y'all,

in the FAQ (https://rsnapshot.org/faq.html) the link to the HOWTO is broken.
It is currently pointing to https://rsnapshot.org/howto/1.2/rsnapshot-HOWTO.en.html#restoring_backups.

**Comment by sam-at-github** [comment]
Duplicate of #92. Also see #106.

**Comment by daniel-wtd** [comment]
I think you meant #93 , thanks a lot. will wait for #106

**Comment by sgpinkus** [comment]
Thanks updated comment.
