### ISSUE TITLE
sync_first should not depend on a backup

### ISSUE THREAD

**Issue by mmitch** [rsnapshot/rsnapshot#233]
**my setup:**

I have a rsnapshot configuration using `sync_first` where rsnapshot resides on the remote server and it's only job is the rotation of the backups. The copy from the local client to the remote server is done by an rsync call on the local client that syncs to the `.sync` directory on the remote server.

So on the remote server, I run the rotation commands (`hourly`, `daily`, `weeky`, `montly`), but I *don't* run the `sync` command because that is done by the local client.

**what happens (bug encountered):**

Unfortunately, running the `hourly` rotation gives this error:
```
ERROR: At least one backup point must be set. rsnapshot can not continue.
```

**what did I expect to happen:**

The backup point is only used by the `sync` command which I don't run.
A rotation should work without a backup point.

**workaround:**

I have added a bogus `backup` line to my configuration that contains a bogus source and target directory. This makes the rotation work.

**Comment by sam-at-github** [comment]
True but only because you are using `sync_first`. rsnapshot with and without `sync_first` is really very different. I think the workaround is obvious and not worth fixing.
