### ISSUE TITLE
Rm one of the duplicate(?) HOWTOs

### ISSUE THREAD

**Issue by sam-at-github** [rsnapshot/rsnapshot#234]
Noticed (#214) there is two versions of the HOWTO in the repo that seem to be independent:

```
[sam@localhost docbook]$tree
.
├── Makefile
├── README
├── rest.html
├── rest.mk
├── rest.pdf
├── rest.txt
├── rsnapshot-HOWTO.en.fo
├── rsnapshot-HOWTO.en.info
├── rsnapshot-HOWTO.en.pdf
├── rsnapshot-HOWTO.en.xhtml
└── rsnapshot-HOWTO.en.xml
```

Unless I'm missing something, rest.mk generates rest.{pdf,html} from rest.txt. Makefile generates rsnapshot-HOWTO.en.{fo,info,pdf,xhtml} from rsnapshot-HOWTO.en.xml. Should probably just keep one around. Easier to maintain. No confusion as to which is more upto date. Quesiotn is which one? The RST (rest.txt) renders nicer (IMO), but the rsnapshot-HOWTO.en.xml has some version history in it not present in the rest.txt. @DrHyde, @bebehei. do you know what the deal is with these files, which one we should keep / both?

**Comment by davidcantrelluk2** [comment]
My preferred approach would be to extract the most up-to-date text, convert it to POD, and delete the docbook version.

**Comment by sam-at-github** [comment]
:+1: for deleting the docbook. I don't know how to easily convert restructuredText to POD though. Maybe just keep the restructuredText (i.e. the rest.txt file and rest.mk Makefile) for now and can look at converting to pod later? I'll make sure there is nothing in the docbook that is not in rest.txt.

**Comment by StefanMoch** [comment]
Although it does not seem to support POD as an output format, you might have a look at [pandoc](https://pandoc.org/), (only found [Pod::Pandoc](https://metacpan.org/pod/Pod::Pandoc) to use it as an input), it may save some work if used to convert it all to restructuredText first and use that as a base for integrating into existing POD or manually converting to POD text.

**Comment by davidcantrelluk2** [comment]
I expect that converting to Pod would be a Small Matter Of Programming. I'd actually start with the HTML version to avoid learning whatever restructuredText is, as that appears to use h1/h2/h3 tags to indicate the document structure, nice clean <p> for body text, and <pre> for example commands etc. Once it's in Pod it's dead easy to edit and dead easy to convert to any other common documentation format.

**Comment by sam-at-github** [comment]
@DrHyde  I just deleted the rest.\*. See linked RP. The content is exactly the same but the rsnapshot-HOWTO.en.\* contain slightly more meta data (document version history). Like you mention the latter will be easier to convert to Pod. Unfortunately I don't have time to look into it that in the scope of this ticket. Can be done as future next step. 

See
