### ISSUE TITLE
Release 1.4.3

### ISSUE THREAD

**Issue by sam-at-github** [rsnapshot/rsnapshot#235]
Master has progressed quite far from 1.4.2 tag and has some fixes in it. Probably time to tag another release. I will do so in next week or two if no objections. Only thing I can think I want to add is minor tidy up rel the HOWTO and once over on the man page so can point to it as main documentation (noticed doesn't render too nice on [linux.die.net](https://linux.die.net/man/1/rsnapshot), but may by old version, not sure). Refs #234 #129

**Comment by MTecknology** [comment]
Are you still working on a release? :)

**Comment by sam-at-github** [comment]
Yes! Pushed it to the back burner. Will get it done this weekend. Just wanted to tidy up some doc and it's done. Thanks for reminding me ;).

**Comment by bebehei** [comment]
I'd appreciate that you clear up #191 first. A release contradicts a project with an "unmaintained" notice.

**Comment by sam-at-github** [comment]
I am temporarily maintaining it I guess I'm just not "maintainer". Is this not acceptable? There is not much to do other than tag a commit, just wanted to take the op to tidy up some doc. After this one I don't see myself doing much maintenance just because it isn't necessary.

**Comment by BassemN** [comment]
I hope you release 1.4.3 soon

**Comment by sam-at-github** [comment]
Tagged 1.4.3.
