### ISSUE TITLE
log pid in $run_string

### ISSUE THREAD

**Issue by kberry** [rsnapshot/rsnapshot#236]
I've been needing to experiment with the cron timings so that rsnapshot jobs don't overlap, resulting in "Lockfile /var/run/rsnapshot.pid exists and so does its process NNNN" errors.

For that purpose, it would be helpful to include te pid in the log file messages, to make it easier to correlate. Although all the information is there anyway, it just simplifies understanding what is happening. The change is trivial, around line 167:

orig: `my $run_string = "$0 " . join(' ', @ARGV);`
rev:  `my $run_string = "$0 " . join(' ', @ARGV) . " [$$]";`

For your consideration. And thanks for rsnapshot.

**Comment by sam-at-github** [comment]
I get this message:

> ERROR: Lockfile /path/to/lock/file exists and so does its process, can not continue

Why not just look inside the lock file for the pid?

**Comment by kberry** [comment]
i'm getting the lock file exists error in email, usually many hours after all the related processes are gone. Having the pid in the rsnapshot log just makes it simple to understand exactly which rsnapshot process logged each line. When there can be several rsnapshots involved, it's not always obvious. At least it wasn't to me.

**Comment by sam-at-github** [comment]
I think this conflicts with the meaning of what `run_string` is: comment says "exactly how the program was called, with all arguments" so adding the pid probably not wise.

Note if not you can also wrap you invocation to rsnapshot and log whatever. A lot of 

Note, syslog should be logging the PID of the process to allow you to distinguish which process was making the logs. Example this is what the above looks like in the syslog:

> Aug 20 08:42:01 master CRON[9325]: (root) CMD (rsnapshot -c /path/to/rsnapshot.conf sync)
Aug 20 08:42:01 master CRON[9296]: (root) CMD (rsnapshot -c /path/to/rsnapshot.conf daily)
Aug 20 08:42:01 master rsnapshot[9297]: /usr/bin/rsnapshot -c /path/to/rsnapshot.conf daily: ERROR: Lockfile /path/to/rsnapshot-test.lock exists and so does its process, can not continue

Your suggestion in #237 is simple and could make this sequence of logs a bit easier to trace so is probably worth considering, but closing this one.

**Comment by kberry** [comment]
clearly it doesn't have to be done by changing run_string. that was just the most expedient method for me to figure out the problem so i could get on with life. also, in practice, $run_string is only used for making the logs, as far as i could tell, in which case you could also just change its description.

the rsnapshot log file contains many invocations of the cron jobs. sure, the syslog file has the pids, but it is not trivial to match up the syslog logs with the rsnapshot logs, as i said. it can be done, or i wouldn't have bothered to take the time to change the code and submit the idea. the more efficient debugging problems can be, the better.

but i expect no changes. my whole problem has gone away with the advent of use_lazy_deletes, so it's not an issue for me any more.
