### ISSUE TITLE
allow sym links to a specific backup

### ISSUE THREAD

**Issue by bje-** [rsnapshot/rsnapshot#240]
Sometimes it is convenient to make a symlink to a specific backup as we do with tags in revision control systems. For example:

`ln -s /snapshots/beta.0 /snapshots/before-big-conversion`

Users can already create such links for themselves, of course. Some assistance is required from rsnapshot, though, to advance the symlink so that it follows the backup as it moves through the cycle. When the backup is ultimately expired, the symlink can also be removed.

Perhaps this behaviour could be a boolean option in `rsnapshot.conf` that defaults to off?

If this idea is welcome, I am happy to work on a patch.

**Comment by sgpinkus** [comment]
I think this overkill. Can you not just touch a file with the directory to label it? This type of labelling is done for example by `tar  --exclude-caches`.

**Comment by bje-** [comment]
OK, fair enough.
