### ISSUE TITLE
rsnapshot error "umount: [path]: not mounted"

### ISSUE THREAD

**Issue by bjmuld** [rsnapshot/rsnapshot#241]
In debugging other lvm problems (zombie lvm snapshot preventing rsnapshot from running), I came across this one.

Its unclear why /bin/umount would return anything other than 0 here; particularly why it would report that the device isn't mounted.

manually retracing steps (with sudo) yields a normal unmount without error.
It seems as though the subsequent call to `/bin/lvremove ` works fine and everything continues okay.

Is it possible this is related to the creation of zombie LVs ?

**Comment by sgpinkus** [comment]
Haven't dug into it but it's possible there are some error scenarios where rsnapshot will bail without successfully cleaning up the snapshot. Can't do much w/o more details on how to reproduce.
