### ISSUE TITLE
Suggestion: merge rsnapshot-ng

### ISSUE THREAD

**Issue by AndiDittrich** [rsnapshot/rsnapshot#247]
Hi @sgpinkus ,

first of all - thanks for maintaining rsnapshot! :+1: 

Maybe you can suggest to merge [rsnapshot-ng](https://github.com/AenonDynamics/rsnapshot-ng) in the future as major release (v2). I've created the fork when rsnapshot was unmaintained.

it includes a new project structure, [Node.js based testcases](https://github.com/AenonDynamics/rsnapshot-ng/tree/ng/test), full [systemd support](https://github.com/AenonDynamics/rsnapshot-ng/tree/ng/systemd) and i've removed all the old/deprecated stuff as well as some minor enhancements (new config parser regex with space delimiters).

due to some breaking changes it cannot by merged into the current v1 branch.

best regards, Andi

**Comment by sgpinkus** [comment]
Well, rsnapshot-ng looks about as well maintained as rsnapshot these days :). Prefer to keep it all under one roof.

Pretty sure we want to pull in deps on Node.js and systemd. Not sure what "supporting systemd" entails, except for unit files, but that is well documented lots of places. If it entails more than that then I'm definitely sure we don't want that.

Cheers.
