### ISSUE TITLE
--max-size rsync option not working

### ISSUE THREAD

**Issue by alexandercch** [rsnapshot/rsnapshot#251]
I have a rsnapshot config file with arguments for rsync as follows:

rsync_long_args	--no-group	--bwlimit=25000	--times	--compress	--recursive	--delete	--ignore-errors	--inplace	--quiet	--max-size=15m

so, here I'm telling rsync to exclude files above 15 MiB, when i check the destination of the copy i see files above the max-size param, when i run  rsync only with these options, the parameter is being taken into account, so it is maybe an additional configuration on rsnapshot that I'm missing or it is a bug

**Comment by StefanMoch** [comment]
Please check if these are files, which were in your backup before you started to use this option.

rsync's `--max-size` option only affects transfer of files. From the man page:
```
              This  option  is  a transfer rule, not an exclude, so it doesn’t
              affect the data that goes  into  the  file-lists,  and  thus  it
              doesn’t affect deletions.  It just limits the files that the re‐
              ceiver requests to be transferred.
```

**Comment by StefanMoch** [comment]
@alexandercch Can this issue be closed?

**Comment by alexandercch** [comment]
Yes, please, close the issue.
