### ISSUE TITLE
Danger of incomplete snapshot

### ISSUE THREAD

**Issue by zpdcodes** [rsnapshot/rsnapshot#253]
Is it possible that a snapshot is incomplete if the rsnapshot running process is interrupted? Is there any buffering/intermediate folder before turning into a real snapshot folder? Actually I'm worrying there's no easy way to verify if a snapshot is incomplete, which might cause file missing in future restore of snapshots.

**Comment by DrHyde** [comment]
If you use sync_first then you should be OK IIRC.

If you don't then yes, that might happen, but you would also expect to get a whiny email from cron telling you that it didn't complete cleanly.

Please in future use the mailing list for questions, Github issues are for reporting bugs, and most people who can answer your questions aren't part of the Github project.

**Comment by zpdcodes** [comment]
@DrHyde Thanks for reply. Sorry for missing the mailing list.
