### ISSUE TITLE
Backup with ' '

### ISSUE THREAD

**Issue by vboa68** [rsnapshot/rsnapshot#255]
Hi all
I ran rsnapshot daily remotely from one HD on usb-raspberry to another HD on usb-tinkerboard.
Since last week it worked fine... but today on HD usb-raspberry (used as backup), I saw that files have been copied but directory is ' '. See the attached file.

Do you know why? How to fix this issue?
thanks
Vinx
![rsnapshot](https://user-images.githubusercontent.com/17923557/78264372-62227b00-7503-11ea-932b-c532312a7d31.JPG)

**Comment by DrHyde** [comment]
Show us your config file and the log of when that backup happened (normally in /var/log/rsnapshot or similar), then maybe someone can figure it out. It's probably some incorrect or missing "quoting" around a path somewhere in there.

**Comment by vboa68** [comment]
Hi

thanks.. attached the config and the log of today night
vincenzo
[rsnapshot_config.txt](https://github.com/rsnapshot/rsnapshot/files/4425520/rsnapshot_config.txt)
[rsnapshot_log.txt](https://github.com/rsnapshot/rsnapshot/files/4425521/rsnapshot_log.txt)

**Comment by vboa68** [comment]
Sstill having  issue

**Comment by sgpinkus** [comment]
Classic space instead of tabs :) rsnapshot config line parameters must be separated with tabs, not spaces.

**Comment by vboa68** [comment]
all parameters are separated by spaces... also because otherwise the rsnapshot configtest advices me about errors... :-)

**Comment by sgpinkus** [comment]
Well, replacing the spaces with tabs where they are intended to be separating parameters is a step in the right direction. Then you'll need to deal with the errors.

**Comment by sgpinkus** [comment]
Up

**Comment by vboa68** [comment]
hi

thanks for your hint.
I decided to copy back again the rsnapshot.conf default file, and re-make the configuration ensuring that tab is used instead of space.
Result --> now it seems working fine.
Let's see tomorrow morning 

thanks again
vincenzo

**Comment by DrHyde** [comment]
Another thing that I should have mentioned originally is that the rsnapshot-discuss mailing list is a better place for initial support queries. Anyway, glad it's now working for you.
