### ISSUE TITLE
how to move rsnapshot backup folder to external disk ?

### ISSUE THREAD

**Issue by changchichung** [rsnapshot/rsnapshot#257]
I have a node running rsnapshot for years .
but couple days ago , the raid just failed for one disk offline.

I want to move the backup folder (about 8 terabytes) to external disk.
but with rsync or cp , they always follow the link so each folder in rsnapshot backup folder will contain full size of backupfiles.

according to rsync man page I try 
```
rsync -rLkv /home/chchang/backup /tmp/backup
or 
rsync -rlkv /home/chchang/backup /tmp/backup
```

always copy all backupfiles , not the link .

any other suggestions ??

**Comment by changchichung** [comment]
found it !
```
rsync -rH source dest 
```
will do the job !

**Comment by DrHyde** [comment]
Please post usage questions to the mailing list instead of opening issues.
