### ISSUE TITLE
file privilegs not copied

### ISSUE THREAD

**Issue by Ernestopheles** [rsnapshot/rsnapshot#260]
I did the first Backup after installation of rsnapshot, from a remote server to my local machine. Backup succeded but files do not have any privilegs.

**Comment by DrHyde** [comment]
On 23/06/2020 20:06, Ernst wrote:
> I did the first Backup after installation of rsnapshot, from a remote 
> server to my local machine. Backup succeded but files do not have any 
> privilegs.

Did you run rsnapshot as root? If you didn't then it might not be able 
to write appropriate permissions. And remember that rsnapshot generally 
only copies POSIX permissions. If you have any non-standard perms then 
those can't be reliably copied.

-- 
David Cantrell
