### ISSUE TITLE
Making relative includes via include_conf more viable

### ISSUE THREAD

**Issue by stefanct** [rsnapshot/rsnapshot#261]
Hi,
I would like to include a common config file in multiple top-level config files without using absolute paths (to ease sharing on multiple computers). This is not exactly trivial because there is no information provided to the script environment of `include_conf`. Thus one has to resort to parsing the `/proc` directory of the parent process (perl) for example:

	include_conf	`/bin/cat $(dirname $(realpath /proc/$PPID/fd/3))/../rsnapshot_common.conf`
	include_conf	`/bin/cat /proc/$PPID/cwd/$(dirname $(getopt -qu "c:" $(cat /proc/$PPID/cmdline  | tr '\000' ' ') | cut -f3 -d' ' ))/../rsnapshot_common.conf`

The first one relies on the fact that the top-level config file is opened as FD 3, while the second one parses the command line and expects `-c <config file>` to be used. Both are of horrendous obviously. :) I have not dared to test nesting.

If the perl code would export some environment variable like `RSNAPSHOT_CONF_FILE` or so this could be dramatically simplified and it might be useful in some other cases.

Alternatively, how about properly supporting relative paths directly (without back-ticks)? Currently they are relative to the CWD (i.e. from where rsnapshot was started) - it would make more sense to make them relative to the config file that contains the respective `include_conf` statement IMHO.

What do you think?

**Comment by sgpinkus** [comment]
> If the perl code would export some environment variable like RSNAPSHOT_CONF_FILE or so this could be dramatically simplified and it might be useful in some other cases.

As a work around you can easily export that variable yourself before you run rsnapshot.

**Comment by stefanct** [comment]
Of course one can work around this externally, that's not the point. So I presume this means the lack of support for relative paths is a WONTFIX, right?

**Comment by sgpinkus** [comment]
Yes, we won't fix because there is an easy work around. There are a number of cases that crop up for rsnapshot for which there are easy workarounds and we feel probably fall outside of the responsibilities of rsnapshot. This is one of those. I think it's the same for any software, rsnapshot maybe more so than newer less stable software projects.

Cheers.
