### ISSUE TITLE
backup_exec with date not working

### ISSUE THREAD

**Issue by evasil** [rsnapshot/rsnapshot#263]
Hello,

there is an example in original config file (was there for ages) as below:
`
backup_exec    /bin/date "+ backup of example.com started at %c"`

That command actually does nothing, it just prints the line as it is in the log as below:
`
/bin/date "+ backup of example.com started at %c"`

The same command in shell runs as expected:

```
# /bin/date "+ backup of example.com started at %c"
backup of example.com started at Чт 10 сен 2020 13:19:46
```

How to reproduce:

1. install rsnapshot
2. configure any job, eg. "hourly"
3. add the line:
`backup_exec    /bin/date "+ backup of example.com started at %c"`
4. test the job with:
rsnapshot -t hourly
5. Log output will print the line as it is, not executing it:
`/bin/date "+ backup of example.com started at %c"`

**Comment by sgpinkus** [comment]
**Test configuration:**

```
config_version	1.2
snapshot_root	/tmp/snapshots/
cmd_rm		/usr/bin/rm
cmd_rsync	/usr/bin/rsync
cmd_logger	/usr/bin/logger
retain	alpha	6
lockfile	/tmp/rsnapshot.pid
backup_exec	/bin/date "+ backup of example.com started at %c"
```

**Test results:**

```
$ rsnapshot -c rsnapshot.263.conf  alpha
 backup of example.com started at Fri 09 Oct 2020 02:03:29 PM AEDT
```

Closed.
