### ISSUE TITLE
sync FAILs, "ERROR: /usr/bin/rsync syntax or usage error. Does this version of rsync support --link-dest", with "rsync --link-dest" *available* ?

### ISSUE THREAD

**Issue by pgnd** [rsnapshot/rsnapshot#265]
i've installed
```
	grep PRETTY /etc/os-release
		PRETTY_NAME="Fedora 32 (Server Edition)"
	rpm -qa | grep rsnapshot
		rsnapshot-1.4.3-2.fc32.noarch
```

rsnapshot config,
```
	config_version	1.2
	snapshot_root	/srv/backups/rsnapshot
	no_create_root	0

	cmd_cp	/usr/bin/cp
	cmd_rm	/usr/bin/rm
	cmd_rsync	/usr/bin/rsync
	cmd_ssh	/usr/bin/ssh
	cmd_logger	/usr/bin/logger
	cmd_du	/usr/bin/du
	cmd_rsnapshot_diff	/usr/bin/rsnapshot-diff

	linux_lvm_cmd_lvcreate	/usr/sbin/lvcreate
	linux_lvm_cmd_lvremove	/usr/sbin/lvremove
	linux_lvm_cmd_mount	/usr/bin/mount
	linux_lvm_cmd_umount	/usr/bin/umount

	## BACKUP LEVELS / INTERVALS
	retain	alpha	6
	retain	beta	7
	retain	gamma	4

	## GLOBAL OPTIONS
	verbose	2
	loglevel	3
	logfile	/var/log/rsnapshot/log
	lockfile	/run/rsnapshot.pid
	one_fs	1
	link_dest	1
	sync_first	1
	use_lazy_deletes	1
	rsync_numtries	0

	linux_lvm_snapshotsize	100M
	linux_lvm_snapshotname	snap_rsnapshot
	linux_lvm_vgpath	/dev
	linux_lvm_mountpath	/mnt/RSNAPSHOT

	## BACKUP POINTS
	backup	/usr/local/etc/test/	TEST.BKUP/
	backup	lvm://VG0/LV_TEST/	TEST.BKUP/LV_TEST
```

where
```
	ls -ald /usr/local/etc/test
		drwx------ 6 devid devid 4.0K Sep 21 20:33 /usr/local/etc/test/
	vgs
		VG      #PV #LV #SN Attr   VSize   VFree
		VG0       1  10   0 wz--n- 930.06g 679.06g
	lvs
		LV                VG      Attr       LSize  Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
		...
		LV_TEST           VG0     -wi-ao----  5.00g
```

and
```
	rsync --help | grep link-dest
		--link-dest=DIR          hardlink to files in DIR when unchanged
```

on exec of sync, first,
```
	tree /srv/backups/rsnapshot
		/srv/backups/rsnapshot

		0 directories, 0 files

	rsnapshot sync
		----------------------------------------------------------------------------
		rsnapshot encountered an error! The program was invoked with these options:
		/usr/bin/rsnapshot sync
		----------------------------------------------------------------------------
		ERROR: /usr/bin/rsync syntax or usage error. Does this version of rsync support --link-dest?
		ERROR: /usr/bin/rsync syntax or usage error. Does this version of rsync support --link-dest?

	tree /srv/backups/rsnapshot
		/srv/backups/rsnapshot

		0 directories, 0 files
```

repeating, with -D
```
	rsnapshot -D sync
		require Lchown
		Lchown module loaded successfully
		Setting locale to POSIX "C"
		echo 16559 > /run/rsnapshot.pid 
		/usr/bin/rsync -av --delete --numeric-ids --relative --delete-excluded \
			/usr/local/etc/test/ \
			/srv/backups/rsnapshot/.sync/TEST.BKUP/ 
		----------------------------------------------------------------------------
		rsnapshot encountered an error! The program was invoked with these options:
		/usr/bin/rsnapshot -D sync 
		----------------------------------------------------------------------------
		ERROR: /usr/bin/rsync syntax or usage error. Does this version of rsync support --link-dest?
		/usr/bin/logger -p user.err -t rsnapshot[16559] /usr/bin/rsnapshot -D sync: \
			ERROR: /usr/bin/rsync syntax or usage error. Does this version of rsync \
			support --link-dest? 
		/usr/sbin/lvcreate --snapshot --size 100M --name snap_rsnapshot \
			/dev/VG0/LV_TEST
		/usr/bin/mount /dev/VG0/snap_rsnapshot /mnt/RSNAPSHOT
		chdir(/mnt/RSNAPSHOT)
		/usr/bin/rsync -av --delete --numeric-ids --relative --delete-excluded ./ \
			/srv/backups/rsnapshot/.sync/TEST.BKUP/LV_TEST
		ERROR: /usr/bin/rsync syntax or usage error. Does this version of rsync support --link-dest?
		/usr/bin/logger -p user.err -t rsnapshot[16559] /usr/bin/rsnapshot -D sync: \
			ERROR: /usr/bin/rsync syntax or usage error. Does this version of rsync \
			support --link-dest?
		chdir(/srv/backups/rsnapshot)
		/usr/bin/umount /mnt/RSNAPSHOT
		/usr/sbin/lvremove --force /dev/VG0/snap_rsnapshot
		touch /srv/backups/rsnapshot/.sync/
		rm -f /run/rsnapshot.pid
		No directory to delete: /srv/backups/rsnapshot/_delete.16559
		/usr/bin/logger -p user.err -t rsnapshot[16559] /usr/bin/rsnapshot -D sync: \
			ERROR: /usr/bin/rsnapshot -D sync: completed, but with some errors
```

what's missing in required usage/config?
or a bug?

**Comment by StefanMoch** [comment]
Please try `rsnapshot -D sync` again with
```
link_dest	0
```
and post the output of it.


The log shows that the rsync calls do not actually contain the `--link-dest` option, which is only appended if there is a previous backup in the snapshot_root to choose from. However an exit code of `1` from `rsync` along with the `link_dest	1` config triggers this error message, which is misleading in this case..

You can also try to manually run the rsync calls from the output above without rsnapshot, to see what rsync complains about.

**Comment by pgnd** [comment]
edit
```
-	link_dest	1
+	link_dest	0
	sync_first	1
	use_lazy_deletes	1
	rsync_numtries	0
```

exec
```
rsnapshot -D sync
	require Lchown
	Lchown module loaded successfully
	Setting locale to POSIX "C"
	echo 29277 > /run/rsnapshot.pid 
	/usr/bin/cp -al /srv/backups/rsnapshot/alpha.0 \
		/srv/backups/rsnapshot/.sync
	/usr/bin/rsync -av --delete --numeric-ids --relative --delete-excluded \
		/usr/local/etc/test/ \
		/srv/backups/rsnapshot/.sync/TEST.BKUP/
	----------------------------------------------------------------------------
	rsnapshot encountered an error! The program was invoked with these options:
	/usr/bin/rsnapshot -D sync
	----------------------------------------------------------------------------
	ERROR: /usr/bin/rsync returned 1 while processing /usr/local/etc/test/
	/usr/bin/logger -p user.err -t rsnapshot[29277] /usr/bin/rsnapshot -D sync: \
		ERROR: /usr/bin/rsync returned 1 while processing \
		/usr/local/etc/test/
	/usr/sbin/lvcreate --snapshot --size 100M --name snap_rsnapshot \
		/dev/VG0/LV_TEST
	/usr/bin/mount /dev/VG0/snap_rsnapshot /mnt/RSNAPSHOT
	chdir(/mnt/RSNAPSHOT)
	/usr/bin/rsync -av --delete --numeric-ids --relative --delete-excluded ./ \
		/srv/backups/rsnapshot/.sync/TEST.BKUP/LV_TEST
	ERROR: /usr/bin/rsync returned 1 while processing lvm://VG0/LV_TEST/
	/usr/bin/logger -p user.err -t rsnapshot[29277] /usr/bin/rsnapshot -D sync: \
		ERROR: /usr/bin/rsync returned 1 while processing \
		lvm://VG0/LV_TEST/
	chdir(/srv/backups/rsnapshot)
	/usr/bin/umount /mnt/RSNAPSHOT
	/usr/sbin/lvremove --force /dev/VG0/snap_rsnapshot
	touch /srv/backups/rsnapshot/.sync/
	rm -f /run/rsnapshot.pid
	No directory to delete: /srv/backups/rsnapshot/_delete.29277
	/usr/bin/logger -p user.err -t rsnapshot[29277] /usr/bin/rsnapshot -D sync: \
		ERROR: /usr/bin/rsnapshot -D sync: completed, but with some errors
```


otoh, manually
```
/usr/bin/rsync -av --delete --numeric-ids --relative --delete-excluded \
 /usr/local/etc/test/ \
 /srv/backups/rsnapshot/.sync/TEST.BKUP/
```

works as expected, with _no_ error

**Comment by aekewu** [comment]
> i've installed
> 
> ```
> 
> 	grep PRETTY /etc/os-release
> 
> 		PRETTY_NAME="Fedora 32 (Server Edition)"
> 
> 	rpm -qa | grep rsnapshot
> 
> 		rsnapshot-1.4.3-2.fc32.noarch
> 
> ```
> 
> 
> 
> rsnapshot config,
> 
> ```
> 
> 	config_version	1.2
> 
> 	snapshot_root	/srv/backups/rsnapshot
> 
> 	no_create_root	0
> 
> 
> 
> 	cmd_cp	/usr/bin/cp
> 
> 	cmd_rm	/usr/bin/rm
> 
> 	cmd_rsync	/usr/bin/rsync
> 
> 	cmd_ssh	/usr/bin/ssh
> 
> 	cmd_logger	/usr/bin/logger
> 
> 	cmd_du	/usr/bin/du
> 
> 	cmd_rsnapshot_diff	/usr/bin/rsnapshot-diff
> 
> 
> 
> 	linux_lvm_cmd_lvcreate	/usr/sbin/lvcreate
> 
> 	linux_lvm_cmd_lvremove	/usr/sbin/lvremove
> 
> 	linux_lvm_cmd_mount	/usr/bin/mount
> 
> 	linux_lvm_cmd_umount	/usr/bin/umount
> 
> 
> 
> 	## BACKUP LEVELS / INTERVALS
> 
> 	retain	alpha	6
> 
> 	retain	beta	7
> 
> 	retain	gamma	4
> 
> 
> 
> 	## GLOBAL OPTIONS
> 
> 	verbose	2
> 
> 	loglevel	3
> 
> 	logfile	/var/log/rsnapshot/log
> 
> 	lockfile	/run/rsnapshot.pid
> 
> 	one_fs	1
> 
> 	link_dest	1
> 
> 	sync_first	1
> 
> 	use_lazy_deletes	1
> 
> 	rsync_numtries	0
> 
> 
> 
> 	linux_lvm_snapshotsize	100M
> 
> 	linux_lvm_snapshotname	snap_rsnapshot
> 
> 	linux_lvm_vgpath	/dev
> 
> 	linux_lvm_mountpath	/mnt/RSNAPSHOT
> 
> 
> 
> 	## BACKUP POINTS
> 
> 	backup	/usr/local/etc/test/	TEST.BKUP/
> 
> 	backup	lvm://VG0/LV_TEST/	TEST.BKUP/LV_TEST
> 
> ```
> 
> 
> 
> where
> 
> ```
> 
> 	ls -ald /usr/local/etc/test
> 
> 		drwx------ 6 devid devid 4.0K Sep 21 20:33 /usr/local/etc/test/
> 
> 	vgs
> 
> 		VG      #PV #LV #SN Attr   VSize   VFree
> 
> 		VG0       1  10   0 wz--n- 930.06g 679.06g
> 
> 	lvs
> 
> 		LV                VG      Attr       LSize  Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
> 
> 		...
> 
> 		LV_TEST           VG0     -wi-ao----  5.00g
> 
> ```
> 
> 
> 
> and
> 
> ```
> 
> 	rsync --help | grep link-dest
> 
> 		--link-dest=DIR          hardlink to files in DIR when unchanged
> 
> ```
> 
> 
> 
> on exec of sync, first,
> 
> ```
> 
> 	tree /srv/backups/rsnapshot
> 
> 		/srv/backups/rsnapshot
> 
> 
> 
> 		0 directories, 0 files
> 
> 
> 
> 	rsnapshot sync
> 
> 		----------------------------------------------------------------------------
> 
> 		rsnapshot encountered an error! The program was invoked with these options:
> 
> 		/usr/bin/rsnapshot sync
> 
> 		----------------------------------------------------------------------------
> 
> 		ERROR: /usr/bin/rsync syntax or usage error. Does this version of rsync support --link-dest?
> 
> 		ERROR: /usr/bin/rsync syntax or usage error. Does this version of rsync support --link-dest?
> 
> 
> 
> 	tree /srv/backups/rsnapshot
> 
> 		/srv/backups/rsnapshot
> 
> 
> 
> 		0 directories, 0 files
> 
> ```
> 
> 
> 
> repeating, with -D
> 
> ```
> 
> 	rsnapshot -D sync
> 
> 		require Lchown
> 
> 		Lchown module loaded successfully
> 
> 		Setting locale to POSIX "C"
> 
> 		echo 16559 > /run/rsnapshot.pid 
> 
> 		/usr/bin/rsync -av --delete --numeric-ids --relative --delete-excluded \
> 
> 			/usr/local/etc/test/ \
> 
> 			/srv/backups/rsnapshot/.sync/TEST.BKUP/ 
> 
> 		----------------------------------------------------------------------------
> 
> 		rsnapshot encountered an error! The program was invoked with these options:
> 
> 		/usr/bin/rsnapshot -D sync 
> 
> 		----------------------------------------------------------------------------
> 
> 		ERROR: /usr/bin/rsync syntax or usage error. Does this version of rsync support --link-dest?
> 
> 		/usr/bin/logger -p user.err -t rsnapshot[16559] /usr/bin/rsnapshot -D sync: \
> 
> 			ERROR: /usr/bin/rsync syntax or usage error. Does this version of rsync \
> 
> 			support --link-dest? 
> 
> 		/usr/sbin/lvcreate --snapshot --size 100M --name snap_rsnapshot \
> 
> 			/dev/VG0/LV_TEST
> 
> 		/usr/bin/mount /dev/VG0/snap_rsnapshot /mnt/RSNAPSHOT
> 
> 		chdir(/mnt/RSNAPSHOT)
> 
> 		/usr/bin/rsync -av --delete --numeric-ids --relative --delete-excluded ./ \
> 
> 			/srv/backups/rsnapshot/.sync/TEST.BKUP/LV_TEST
> 
> 		ERROR: /usr/bin/rsync syntax or usage error. Does this version of rsync support --link-dest?
> 
> 		/usr/bin/logger -p user.err -t rsnapshot[16559] /usr/bin/rsnapshot -D sync: \
> 
> 			ERROR: /usr/bin/rsync syntax or usage error. Does this version of rsync \
> 
> 			support --link-dest?
> 
> 		chdir(/srv/backups/rsnapshot)
> 
> 		/usr/bin/umount /mnt/RSNAPSHOT
> 
> 		/usr/sbin/lvremove --force /dev/VG0/snap_rsnapshot
> 
> 		touch /srv/backups/rsnapshot/.sync/
> 
> 		rm -f /run/rsnapshot.pid
> 
> 		No directory to delete: /srv/backups/rsnapshot/_delete.16559
> 
> 		/usr/bin/logger -p user.err -t rsnapshot[16559] /usr/bin/rsnapshot -D sync: \
> 
> 			ERROR: /usr/bin/rsnapshot -D sync: completed, but with some errors
> 
> ```
> 
> 
> 
> what's missing in required usage/config?
> 
> or a bug?
