### ISSUE TITLE
Warning: Identity file -l not accessible: No such file or directory.

### ISSUE THREAD

**Issue by vboa68** [rsnapshot/rsnapshot#266]
hi guys

I'm becoming mad with this issue.
I've re-installed a fresh copy of rsnapshot in order to copy files between two raspberrys.

In the remote I created a public ssh key and in rsnapshot.conf I've included

snapshot_root   /mnt/USB/data/vb/files/a/
rsync_long_args --stats --delete        --numeric-ids   --relative      --delete-excluded
ssh_args        -p 255  -i      -v      /root/.ssh/id_rsa

for the moment this is what i'd like to backup
backup  root@192.168.1.215:/etc/fstab   Vbtest_IPF/etc/

I've tested:
 sudo ssh root@192.168.1.215 -p 255
it works well

but when I run sudo rsnapshot daily i get:
require Lchown
Lchown module loaded successfully
Setting locale to POSIX "C"
echo 7084 > /var/run/rsnapshot.pid
/bin/rm -rf /mnt/USB/data/vb/files/a/daily.1/
mv /mnt/USB/data/vb/files/a/daily.0/ \
    /mnt/USB/data/vb/files/a/daily.1/
mkdir -m 0755 -p /mnt/USB/data/vb/files/a/daily.0/Vbtest_IPF/
/usr/bin/rsync -av --stats --rsh=/usr/bin/ssh -p 255 -i \
    --link-dest=/mnt/USB/data/vb/files/a/daily.1/Vbtest_IPF/etc/ \
    root@192.168.1.215:/etc/fstab \
    /mnt/USB/data/vb/files/a/daily.0/Vbtest_IPF/etc/
Warning: Identity file -l not accessible: No such file or directory.
ssh: Could not resolve hostname root: Name or service not known
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(235) [Receiver=3.1.2]
----------------------------------------------------------------------------
rsnapshot encountered an error! The program was invoked with these options:
/usr/bin/rsnapshot daily
----------------------------------------------------------------------------
ERROR: /usr/bin/rsync returned 255 while processing root@192.168.1.215:/etc/fstab
/usr/bin/logger -p user.err -t rsnapshot[7084] /usr/bin/rsnapshot daily: \
    ERROR: /usr/bin/rsync returned 255 while processing \
    root@192.168.1.215:/etc/fstab
WARNING: Rolling back "Vbtest_IPF/etc/"
/usr/bin/logger -p user.err -t rsnapshot[7084] WARNING: Rolling back \
    "Vbtest_IPF/etc/"
/bin/cp -al /mnt/USB/data/vb/files/a/daily.1/Vbtest_IPF/etc \
    /mnt/USB/data/vb/files/a/daily.0/Vbtest_IPF/etc
touch /mnt/USB/data/vb/files/a/daily.0/
rm -f /var/run/rsnapshot.pid
/usr/bin/logger -p user.err -t rsnapshot[7084] /usr/bin/rsnapshot daily: \
    ERROR: /usr/bin/rsnapshot daily: completed, but with some errors

any idea?

thanx
vincenzo

**Comment by DrHyde** [comment]
This `ssh_args -p 255 -i -v /root/.ssh/id_rsa` is wrong, that tells ssh to look for an identity file called '-v'. The name of the key file needs to come immediately after the -i.

If that doesn't fix things for you, please re-open the ticket and attach a copy of your config file.

**Comment by vboa68** [comment]
Hi

I've changed something... but still the same issue.

Here it is the conf..:

config_version	1.2

snapshot_root	/mnt/ocUSB/data/vbtb/files/RPI_config/

#no_create_root 1

cmd_cp	/bin/cp
cmd_rm	/bin/rm
cmd_rsync	/usr/bin/rsync
cmd_ssh	/usr/bin/ssh
cmd_logger	/usr/bin/logger
cmd_du	/usr/bin/du
cmd_rsnapshot_diff	/usr/bin/rsnapshot-diff

#cmd_preexec    /path/to/preexec/script
#cmd_postexec   /path/to/postexec/script
#linux_lvm_cmd_lvcreate /sbin/lvcreate
#linux_lvm_cmd_lvremove /sbin/lvremove
#linux_lvm_cmd_mount    /bin/mount
#linux_lvm_cmd_umount   /bin/umount

retain	daily	2

verbose	5
loglevel	5
logfile	/var/log/VB_rsnapshot.log
lockfile	/var/run/rsnapshot.pid

#stop_on_stale_lockfile         0

rsync_long_args	--stats	--delete	--numeric-ids	--relative	--delete-excluded
ssh_args	-p 255  -i	/root/.ssh/vbtink_rsa

#du_args        -csh
#one_fs         0

link_dest	1

#sync_first     0
#use_lazy_deletes       0
#rsync_numtries 0

backup	root@192.168.1.115:/etc/fstab	Vbtest_IPF/etc/

**Comment by joximu** [comment]
still the exact same error message?
please copypaste again...
