### ISSUE TITLE
Snapshots seem to duplicate everything in a folder leading to huge footprint

### ISSUE THREAD

**Issue by chogovadze** [rsnapshot/rsnapshot#268]
Hello everyone,
After researching I can not find a definitive answer. I am using rsnapshot through OMV. The backup is working correctly. However, the process seems to copy everything in the folder even if only a single file changes. I end up with 7 daily folders each weighing around 50 GB, when all that has changed is the existence of a directory. I am wondering if this is normal behaviour or should there be only incremental changes thus reducing the footprint of the snapshots.
Thank you for your time !

**Comment by DrHyde** [comment]
Each daily backup can be expected to look like it takes about the same amount of space, but most of that space is shared between them all. Please do this on the backup server and report back:

```
cd $snapshot_root
du -sch *
```

I would expect to see one large directory and a bunch of smaller ones. If that's not the case please do this and show us the results:

```
cd $snapshot_root
touch foo
ln foo bar
ls -li foo bar
```

**Comment by chogovadze** [comment]
@DrHyde thanks for reaching out ! 
```
cd $snapshot_root
sudo du -sch *
``` 
returns the following

```
30G	daily.0
30G	daily.1
30G	daily.2
30G	daily.3
30G	daily.4
30G	daily.5
182G	total
```

However, I can not create the hard link as it returns `ln: bar: Operation not supported`.

For reference, OMV is running on a raspberry pi 4 as a NAS. Rsnapshot is running as a plugin on the pi.

**Comment by DrHyde** [comment]
> However, I can not create the hard link

That's the problem then. You need to change filesystems to one that supports hard links.
