### ISSUE TITLE
Enable unlimited backups

### ISSUE THREAD

**Issue by ByteEater-pl** [rsnapshot/rsnapshot#270]
Please add a configuration option to retain all snapshots of a level so that adding a new one never causes an old one to be deleted (though it may fail when the destination runs out of space).

**Comment by DrHyde** [comment]
You can just tell it to keep an absurdly large number of snapshots. I have, for example, `interval	yearly	100` because I really doubt that I'll be in any fit state to care when I'm approaching my 150th birthday.
