### ISSUE TITLE
FAQ Update Request - Backing up a Windows 10 / WSL 2 machine to Linux

### ISSUE THREAD

**Issue by tandell** [rsnapshot/rsnapshot#271]
Reasoning:

* This seems like a good candidate for a FAQ but I was unable to locate the file that generates `https://rsnapshot.org/faq.html` to submit a PR. There's no guidance in `CONTRIBUTING.md` for documentation PRs, as well. There also appears some contention about where documentation belongs in other PRs/Issues.
* If someone searches the issues, hopefully this will help them. And not spend a ton of time realizing that a command executed via perl isn't escaped the same as a command executed via bash.
* rsnapshot-version: Ubuntu 20.04 apt managed version: rsnapshot/focal,now 1.4.3-2 

Related to the question: `How do I backup from Windows machines to Linux?`

**Question:** When backing up a Windows machine via `ssh`, how do you use a username with a space in it?
**Answer:** If a username has a space in it, for example 'John Doe', use the `ssh_args` argument in the `backup` command instead of the username being inline with the address. E.g. `ssh_args=-l 'John Doe'`. `rsnapshot` does not currently allow for parsing spaces _before_ the `@` on a backup target. By proving the username via the `-l` argument, we do an end run around the parser. Note, this should be the last argument on the line as there could be some issues parsing the argument with partial quotes.

**Question:** How to use Window 10's OpenSSH server and WSL2 instead of using cwRsync Server.
**Answer:** For Windows 10 (1809+) machines, another option is to use the native OpenSSH server now available in Windows 10 1809 and WSL2. By using the native ssh server, WSL does not have to be running for the backup to occur.
* Install the native [OpenSSH server in powershell](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse).
* Key based access is still required and can be a bit strange, see the following [StackOverflow post answer](https://stackoverflow.com/a/50502015) for what configuration steps are required. 
* Install WSL2 and your Linux distribution of choice. Make sure `rsync` is installed and available in that distribution.
* Use WSL2's `rsync` by including `rsync_long_args='--rsync-path=wsl rsync'` in the `backup` command. Take care with the single quote placement so the configuration will be executed correctly. By providing `wsl rsync`, this executes `rsync` command in WSL  instead of trying to execute it via Windows.

**Question:** When backing up Windows paths, how do I overcome spaces in the path?
**Answer:** To deal with a space in the path, you can simply escape them in the `backup` command. To continue with example user John Doe, to backup their home directory in Windows use the path `/mnt/c/users/John\ Doe/`. If you're curious why escaping the space works here but not for the username, it's because the path is sent to the remote system and _then_ parsed.

Example `backup` command configuration incorporating all three questions:

This assumes that key based access for John Doe is properly configured on the remote system. (And that tabs are used between the fields)

```
backup    192.168.1.2:/mnt/c/users/John\ Doe/    johndoe/    rsync_long_args='--rsync-path=wsl rsync',ssh_args=-l 'John Doe'
```

**Comment by DrHyde** [comment]
I believe the website is stored in https://github.com/rsnapshot/rsnapshot.github.io

**Comment by tandell** [comment]
Thanks, @DrHyde - I've opened https://github.com/rsnapshot/rsnapshot.github.io/pull/8 in that repo for this request.

**Comment by DrHyde** [comment]
And I've put a note in the CONTRIBUTING file pointing people at the website repo
