### ISSUE TITLE
Source directory "/media/foo" doesn't exist

### ISSUE THREAD

**Issue by basti12203** [rsnapshot/rsnapshot#274]
Hello, in my scenario  the source dir is created my `cmd_preexec` so please check the existence of the Source dir after cmd_preexec is executed.

**Comment by sgpinkus** [comment]
The source of you backup is created after the backup script is running? Sounds weird. People see cmd_pre|postexec, and try to shoe horn all possible backup related scripting into. Either that, or they come here and ask for a new feature or change. Just wrap your backup scripts to do what ever you need to do if cmd_pre|postexec don't fit. Example this is how I wrap my rsnapshot backup:

```
#!/bin/bash

function fail() {
  echo "$@"; exit 1;
}

function post() {
  ./backups-post || fail "Post backup failed."
}

cd $(dirname "$BASH_SOURCE")
trap "post" EXIT
./backups-pre || fail "Pre backup failed. Existing."
[[ -d /backups ]] || fail "Backup desination does not exist. Exiting."
rsnapshot -c /etc/backups-rsnapshot/backups-rsnapshot.conf sync && rsnapshot -c /etc/backups-rsnapshot/backups-rsnapshot.conf level0
```

backups-pre mounts an encrypted drive.
