### ISSUE TITLE
Cannot figure out how to use --rsync-path="sudo rsync" in config file

### ISSUE THREAD

**Issue by sdondley** [rsnapshot/rsnapshot#277]
In my config file, placing rsync_long_args into the backup command works:

`backup  admin@172.30.0.163:/var/www/html/wordpress  website/    rsync_long_args='--rsync-path=sudo rsync    --inplace'`

However, trying to do the same but with separate lines does not:

`rsync_long_args --rsync-path='sudo  rsync' --inplace`
`backup  admin@172.30.0.163:/var/www/html/wordpress  website/`

I get an error:

`ERROR: rsync_long_args --rsync-path='sudo rsync' --inplace`

I tried different ways of quoting and spaces vs. tabs but couldn't get any to work.

**Comment by sgpinkus** [comment]
We generally point people to the mailing list for help questions that don't related to a bug or feature.

Anyway .. strange looking error. If you want help, please paste a config that reproduces the error and a more complete command line output. Otherwise this issue will be closed within a week or so.

**Comment by StefanMoch** [comment]
Unrelated to the error: the write mode `rsync --inplace` uses (writing
directly to the destination file) is _in conflict_ with how rsnapshot
handles its snapshots (keeping unchanged files with multiple hardlinks
to the same file).

From the [rsync manual](https://download.samba.org/pub/rsync/rsync.1):
> **--inplace**
> 
> This option changes how rsync transfers a file when its data needs to
> be updated: instead of the default method of creating a new copy of
> the file and moving it into place when it is complete, rsync instead
> writes the updated data directly to the destination file.
>
> This has several effects:
>
>  - Hard links are not broken. **This means the new data will be
>    visible through other hard links to the destination file.**
>    […]

In short: rsnapshot relies on rsync's normal write mode (writing to new
temporary files and renaming them once complete, which in turn leaves
the existing file content accessible through the hardlinks in the older
snapshot directories alone). With `--inplace` you _will overwrite
existing files in old snapshots_ with the new data once the file changed
at the source.

Unless you only keep only _one_ snapshot, in which case you don't need
rsnapshot anyway, you cannot use `rsync --inplace` with rsnapshot.

**Comment by sdondley** [comment]
Thanks for the tip. I'll remove --inplace.
