### ISSUE TITLE
I have noticed this crash, once jailbreak for my device comes out, I’ll fix it.

### ISSUE THREAD

**Issue by aekewu** [rsnapshot/rsnapshot#278]
I have noticed this crash, once jailbreak for my device comes out, I’ll fix it. 

__最初由 @Co2333 在 https://github.com/SailyTeam/Saily/issues/37#issuecomment-779886745 发布__

**Comment by DrHyde** [comment]
Spam. Ticket closed, account reported.

**Comment by sgpinkus** [comment]
Really weird. What's the motivation, just a random bot?

**Comment by DrHyde** [comment]
I suspect that it was supposed to include a dodgy link or a PR that we would blindly merge
