### ISSUE TITLE
need to take a backup of multiple remote server on single snapshot vm

### ISSUE THREAD

**Issue by kaleamolrahuri** [rsnapshot/rsnapshot#286]
We are alredy running one backup on snapshot vm as below

backup  root@Server:/pldata/     ./

so we nned to add nother remote server for snapshot backup(server2)

backup  root@Server2:/pldata/     ./

we have added server2 but config file sysntax getting invalid.
===============================================
Also we had created /etc/rsnapshot_additional.conf for server2
and tried to update in crontab with below parameters

0 0 * * *        /usr/bin/rsnapshot -c /etc/rsnapshot.additional.conf daily
0 20 * * 0        /usr/bin/rsnapshot -c /etc/rsnapshot.additional.conf weekly

so crontab not allowed this.

Request you to please help on this .

Thanks
Amol A. Kale

**Comment by DrHyde** [comment]
You have specified the same location to store both backups. That won't work, each server that you back up needs to be backed up into its own directory.

As for the invalid syntax - you'll need to share your config file for us to help with that, but I expect that you've used spaces where you should have used a tab.

**Comment by kaleamolrahuri** [comment]
Hello Thanks for response,

[root@azploc-nfs-save-pr snapshots]# cat /etc/rsnapshot.conf | grep -i snapshot_root
snapshot_root   /snapshots/
## snapshot_root directory. This is particularly useful if you are backing
## from running simultaneously (and messing up the snapshot_root).
[root@azploc-nfs-save-pr snapshots]# cat /etc/rsnapshot.conf | grep -i pldata
backup  root@10.36.252.110:/pldata/     ./
backup  root@10.36.252.8:/pldata/       /snapshots2/
[root@azploc-nfs-save-pr snapshots]#  rsnapshot configtest
----------------------------------------------------------------------------
rsnapshot encountered an error! The program was invoked with these options:
/bin/rsnapshot configtest
----------------------------------------------------------------------------
ERROR: /etc/rsnapshot.conf on line 233:
ERROR: backup root@10.36.252.8:/pldata/ /snapshots2/
ERROR: ---------------------------------------------------------------------
ERROR: Errors were found in /etc/rsnapshot.conf,
ERROR: rsnapshot can not continue. If you think an entry looks right, make
ERROR: sure you don't have spaces where only t




above we have added diff mount points so even this config also getting error.

Thanks,
Amol A. Kale

**Comment by DrHyde** [comment]
Ticket still closed. Please use the mailing list as requested.

**Comment by kaleamolrahuri** [comment]
Hello Team,
request you to please provide any alternatives /suggestion for this

**Comment by DrHyde** [comment]
Ticket still closed. Please use the mailing list as requested.
