### ISSUE TITLE
config "cmd_rsnapshot_diff" has incorrect path by default

### ISSUE THREAD

**Issue by booshnelli** [rsnapshot/rsnapshot#289]
hi! 

I've noticed a fresh install of rsnapshot 1.4.4 on debian 11 contains the line: `#cmd_rsnapshot_diff      /usr/local/bin/rsnapshot-diff` in its config file by default. now, uncommenting this line and running the configtest throws:
```
ERROR: cmd_rsnapshot_diff /usr/local/bin/rsnapshot-diff - \
         /usr/local/bin/rsnapshot-diff is not executable 
```
Which is true because rsnapshot-diff isn't in `/usr/local/bin/`, it's in `/usr/bin/`. 
(for me atleast!)

I've setup rsnapshot 1.4.4 on a couple debian systems recently & keep forgetting it wont work if i dont change this line haha.

was wondering if this might just be a me problem, and rsnapshot-diff really *is* supposed to be in the local bin, or if that's not the case - then perhaps it indeed would make more sense for the path to be `/usr/bin/rsnapshot-diff` by default.

cheers :)
-alex

**Comment by DrHyde** [comment]
This is a bug. Damned if I know how to fix it though, because the build/configure system is utterly insane.

**Comment by sgpinkus** [comment]
It's an easy fix. There should be a `@bindir` var or something like it that can be used in `rsnapshot.conf.default.in` instead of hardcode. Will take a look.

**Comment by DrHyde** [comment]
Fix merged, so it will be in the next release whenever that is.
