### ISSUE TITLE
The documentation only discusses interval not retain

### ISSUE THREAD

**Issue by poikilos** [rsnapshot/rsnapshot#302]
### Checklist

- [X] I'm reporting a bug
- [X] I've searched the [bugtracker](https://github.com/rsnapshot/rsnapshot/issues) for similar issues, including closed ones.

### What did you do?

- cd rsnapshot-1.4.4
- `./configure --sysconfdir=/etc && sudo make install`
- Read docs/HOWTOs/rsnapshot-HOWTO.en.html#installation
- `cp /etc/rsnapshot.conf.default /etc/rsnapshot.conf`

### What happened?

The resulting conf has "retain" settings but the documentation doesn't describe the configuration that way. The documentation says:
> interval    hourly  6
> interval    daily   7
> 
> It also has some other entries, but you can either ignore them or comment them out for now.
> 
> Please note that the hourly interval is specified first. This is very important. The first interval line is assumed to be the smallest unit of time...

### What did you expect to happen

The documentation should explain that the interval keyword, or say it is deprecated, and describe the retain keyword.

### My configuration

```
#     BACKUP LEVELS / INTERVALS         #
# Must be unique and in ascending order #
# e.g. alpha, beta, gamma, etc.         #
#########################################

retain  alpha   6
retain  beta    7
retain  gamma   4
#retain delta   3
```
(This block was there by default. The rest of the conf is not applicable.)

### Environment

```markdown
OS: Debian 10 (buster)
Filesystem: BTRFS
```

**Comment by DrHyde** [comment]
This is documented [in the manpage](https://github.com/rsnapshot/rsnapshot/blob/master/rsnapshot-program.pl#L6777) but you're right, it should be in the HOWTO as well. Thanks for reporting it.

**Comment by DrHyde** [comment]
PR #303 should fix this.

**Comment by DrHyde** [comment]
That's now merged
