### ISSUE TITLE
Missing release tarball rsnapshot-1.4.5.tar.gz

### ISSUE THREAD

**Issue by robert-scheck** [rsnapshot/rsnapshot#313]
### Checklist

- [X] I'm reporting a bug
- [X] I've searched the [bugtracker](https://github.com/rsnapshot/rsnapshot/issues) for similar issues, including closed ones.

### What did you do?

For rsnapshot 1.4.4, there is a release tarball (https://github.com/rsnapshot/rsnapshot/releases/download/1.4.4/rsnapshot-1.4.4.tar.gz) at GitHub releases. For rsnapshot 1.4.5, there is not. Well, just the auto-generated tarball from GitHub without `./configure`; this seems like a mistake.

### What happened?

Not sure, issue in the build/release chain on your end? ;-)

### What did you expect to happen

https://github.com/rsnapshot/rsnapshot/releases/download/1.4.5/rsnapshot-1.4.5.tar.gz

### My configuration

n/a

### Environment

```markdown
n/a
```

**Comment by sgpinkus** [comment]
I just added manually. Please check download and close issue if all good.

Release process is manual, and a bit tedious. Should automate more but it we're only doing one or two bug fix releases a year and I don't have time for it. I believe @bebehei  had a go at automating Github release page update with proper tar but I can't remember and it obviously doesn't work any more, and I'm not too bothered to fix.

**Comment by robert-scheck** [comment]
Thank you. But the directory hierarchy inside the archive/tarball is strange:

> rsnapshot-1.4.4/configure

vs. 

> rsnapshot-1.4.5-5-gaf84984/configure

Any chance for the "traditional" `<name>-<version>` scheme inside the archive/tarball also for v1.4.5?

**Comment by sgpinkus** [comment]
True. I've updated to traditional style.

**Comment by bebehei** [comment]
> I believe @bebehei  had a go at automating Github release page update with proper tar but I can't remember

Ive got no clue about this either. If there is something necessary to automate it, i dont remember. Maybe there was `make release` for this?

**Comment by robert-scheck** [comment]
> True. I've updated to traditional style.

Works, thank you!

May I kindly suggest to somehow document the release process for future releases?

**Comment by sgpinkus** [comment]
Best doc is to just automate it, or at least most of it. Don't really want to add to official doc just yet, because it's a bit messy and will probably go stale. Plus generating .deb is only something we started doing after Debian maintainer abandoned project, but there is a new guy now. Hope this comment suffices for now:

```
cd ~/src/
git clone git@github.com:rsnapshot/rsnapshot.git
git clone git@github.com:rsnapshot/rsnapshot.github.io.git
cd rsnapshot
git checkout master
edit Changelog
git commit -a -m "Update Changelog."
git tag <new-version>
git push
git checkout debian-build
git merge master
dch --newversion # Generates a new debian/changelog entry. May need to manually tweak changelog.
dpkg-buildpackage -b -kA53455C1 # My signing key.
make tar
tar -xzf rsnapshot-1.4.5-5-gaf84984.tar.gz
mv rsnapshot-1.4.5-5-gaf84984 rsnapshot-1.4.5
tar -cvzf rsnapshot-1.4.5.tar.gz rsnapshot-1.4.5/
cp rsnapshot-1.4.5.tar.gz ~/src/rsnapshot.github.io/downloads
cp ../rsnapshot_1.4.5-1* ~/src/rsnapshot.github.io/downloads
cd ~/src/rsnapshot.github.io/downloads
./sum.sh rsnapshot-1.4.5.tar.gz
ls | ./gen.pl > index.md
git add rsnapshot-1.4.5.*
git commit -a -m "Add rsnapshot_1.4.5 signed .deb and .tar.gz. Regen index.md"
git push origin master
# Now manually add assets to github release page too.
```
