### ISSUE TITLE
man page indicates second parameter to backup_exec needs trailing slash, it doesn't.

### ISSUE THREAD

**Issue by MarktheSpark17** [rsnapshot/rsnapshot#314]
### Checklist

- [X] I'm reporting a bug
- [X] I've searched the [bugtracker](https://github.com/rsnapshot/rsnapshot/issues) for similar issues, including closed ones.

### What did you do?

Added the following to /etc/rsnapshot.conf
backup_exec     mountpoint /smb/nas-aae-01/     required/

### What happened?

[root@nbu-2 ~]# rsnapshot configtest
----------------------------------------------------------------------------
rsnapshot encountered an error! The program was invoked with these options:
/usr/bin/rsnapshot configtest
----------------------------------------------------------------------------
ERROR: /etc/rsnapshot.conf on line 226:
ERROR: backup_exec mountpoint /smb/nas-aae-01/ required/ - requirement \
         level "required/" is invalid
ERROR: ---------------------------------------------------------------------
ERROR: Errors were found in /etc/rsnapshot.conf,
ERROR: rsnapshot can not continue. If you think an entry looks right, make
ERROR: sure you don't have spaces where only tabs should be.

### What did you expect to happen

rsnapshot configtest to succeed.

### My configuration

backup_exec     mountpoint /smb/nas-aae-01/     required/

### Environment

```markdown
OS: CentOS Linux release 7.9.2009 (Core)
Filesystem: XFS
rsnapshot Version     : 1.4.4
```

### Other information

Removing the trailing slash fixes the issue, so the man page just needs updating.

[root@nbu-2 ~]# grep ^backup_exec /etc/rsnapshot.conf
backup_exec     mountpoint /smb/nas-aae-01/     required
[root@nbu-2 ~]# rsnapshot configtest
Syntax OK

**Comment by sgpinkus** [comment]
Yep defs a typo. FIxed on master. Will make it into next release. Thanks for report.
