### ISSUE TITLE
Tabs do not work with rsync_long_args

### ISSUE THREAD

**Issue by JonMurphy** [rsnapshot/rsnapshot#320]
### Checklist

- [X] I'm reporting a bug
- [X] I've searched the [bugtracker](https://github.com/rsnapshot/rsnapshot/issues) for similar issues, including closed ones.

### What did you do?

I added additional parameters to `rsync_long_args` in the `\etc\rsnapshot.conf` file.  There were tabs between the extra parameters.
```
rsync_long_args	--delete --numeric-ids --relative --delete-excluded	--verbose	--itemize-changes
```
Reads like:
```
rsync_long_args<tab>--delete<space>--numeric-ids<space>--relative<space>--delete-excluded<tab>--verbose<tab>--itemize-changes
```

This did not work either:
```
rsync_long_args<tab>--delete<tab>--numeric-ids<tab>--relative<tab>--delete-excluded<tab>--verbose<tab>--itemize-changes
```

### What happened?

The additional `rsync_long_args` of `--verbose` and `--itemize-changes` were completely ignored.  

There are no error messages or warning messages with these log settings:

```
verbose		3

loglevel	4
```

FYI - there is an error if I use ALL spaces between parameters.  (I entered the rsnapshot command incorrectly)
```
[2023-03-06T12:17:09] /usr/bin/rsnapshot test: ERROR: /etc/rsnapshot.conf on line 141:
[2023-03-06T12:17:09] /usr/bin/rsnapshot test: ERROR: rsync_long_args --stats --verbose --itemize-changes --delete \
         --numeric-ids --relative --delete-excluded - missing tabs to \
         separate words - change spaces to tabs. 
[2023-03-06T12:17:09] /usr/bin/rsnapshot test: ERROR: ---------------------------------------------------------------------
[2023-03-06T12:17:09] /usr/bin/rsnapshot test: ERROR: Errors were found in /etc/rsnapshot.conf,
[2023-03-06T12:17:09] /usr/bin/rsnapshot test: ERROR: rsnapshot can not continue. If you think an entry looks right, make
[2023-03-06T12:17:09] /usr/bin/rsnapshot test: ERROR: sure you don't have spaces where only tabs should be.
[2023-03-06T12:17:40] /usr/bin/rsnapshot test: started
```

### What did you expect to happen

All `rsync_long_args` parameters to be accepted as valid and to be recognized.

To allow all tabs between each item.  Like this:
```
rsync_long_args<tab>--delete<tab>--numeric-ids<tab>--relative<tab>--delete-excluded<tab>--verbose<tab>--itemize-changes
```

(Or maybe to allow a mix of tabs and spaces.  Up to author to decide!)

### My configuration

```
rsync_long_args	--delete --numeric-ids --relative --delete-excluded	--verbose	--itemize-changes
```

### Environment

```markdown
OS: Debian 11
Filesystem: ext4

jon@deb11HPZ:~$ uname -a
Linux deb11HPZ 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
```

**Comment by djk20** [comment]
I think this is not a bug.  rsnapshot has a long history of treating tabs differently to spaces.  

Perhaps there is an argument for having better warning/error detection (if you put "rsync_long_args<tab>--alpha --beta<tab>--gamma --delta", then rsnapshot will treat "--gamma --delta" as a comment, it might be worth having a warning that --gamma --delta is being ignored because of the tab, like rsnapshot tries to give a helpful error if there are no tabs).  But if we do that, then we should probably do it for other sort of config as well, like ssh_args, du_args, etc.

**Comment by JonMurphy** [comment]
A logged warning is fine.  Anything to make things a little less confusing.

**Comment by JonMurphy** [comment]
I am thinking of creating a package (add-on) for an linux distro for a firewall.  I created the package and am about ready to release.  But I saw the posts about Debian #279.  Is work continuing on rsnapshot?

**Comment by DrHyde** [comment]
> But I saw the posts about Debian https://github.com/rsnapshot/rsnapshot/issues/279. Is work continuing on rsnapshot?

The last comments on #279 would seem to be relevant :-)

There's not much work being done on rsnapshot, but that's because it's been around for a while and does what it's supposed to. It's stable software so doesn't need constant updating.

**Comment by JonMurphy** [comment]
Yes, I agree.  It definitely does what it is suppose to.  But there are a few updates (pull requests) including one from you.  Will these be added by the author(s)?

And I would also like to add a backup sqlite3 script.  

I just want to make sure things move forward...
