### ISSUE TITLE
Migration to GitHub is not complete

### ISSUE THREAD

**Issue by Neustradamus** [rsnapshot/rsnapshot#332]
### Checklist

- [X] I'm reporting a bug
- [X] I've searched the [bugtracker](https://github.com/rsnapshot/rsnapshot/issues) for similar issues, including closed ones.

### What did you do?

Dear @rsnapshot team, @djk20, @DrHyde, @sgpinkus, @bebehei, @ratherlargerobot,

Can you add a "move" box like https://sourceforge.net/projects/handbrake for example.
- https://sourceforge.net/p/rsnapshot/

To disable/delete tabs, go here: https://sourceforge.net/projects/rsnapshot/
To add a new tab, go here: https://sourceforge.net/projects/rsnapshot/
To change informations, go here: https://sourceforge.net/p/rsnapshot/admin/overview
To export, go here: https://sourceforge.net/p/rsnapshot/admin/export

The new place can be added in:
- "Moved Project to", here: https://sourceforge.net/p/rsnapshot/admin/overview
- A new tab, go here: https://sourceforge.net/projects/rsnapshot/

Please remove:
- https://sourceforge.net/p/rsnapshot/cvs/
- Some or all: https://sourceforge.net/p/rsnapshot/mailman/

Thanks in advance.

### What happened?

Read before.

### What did you expect to happen

Read before.

### My configuration

Read before.

### Environment

```markdown
OS: *
Filesystem: *
```

**Comment by DrHyde** [comment]
We do still use sourceforge's mailing list functionality - it's a real shame that Github don't have this.

If we tell Sourceforge that we've moved does anyone know if they will delete the mailing lists?

**Comment by Neustradamus** [comment]
@DrHyde: I have not specified you to remove all mailing lists ^^

You can remove for example:
- https://sourceforge.net/p/rsnapshot/mailman/rsnapshot-cvs/ (CVS is linked to SF, not used)
- https://sourceforge.net/p/rsnapshot/mailman/rsnapshot-travis/ (it is not used)
- https://sourceforge.net/p/rsnapshot/mailman/rsnapshot-announce/ (it is not used)

**Comment by Neustradamus** [comment]
@DrHyde: Thanks a lot!

Maybe you can add the logo on SF too?

**Comment by DrHyde** [comment]
We don't have a logo

**Comment by Neustradamus** [comment]
@DrHyde: The same than here ^^
- https://github.com/rsnapshot

**Comment by Neustradamus** [comment]
@DrHyde: Can you add the logo of the GitHub organization on Sourceforge?
It will be better to nothing...

**Comment by DrHyde** [comment]
Done!

**Comment by Neustradamus** [comment]
@DrHyde: Thanks a lot! :)
Really better now ^^
