### ISSUE TITLE
AUTHORS invalid current maintainer

### ISSUE THREAD

**Issue by Hikaru512** [rsnapshot/rsnapshot#336]
### Checklist

- [X] I'm reporting a bug
- [X] I've searched the [bugtracker](https://github.com/rsnapshot/rsnapshot/issues) for similar issues, including closed ones.

### What did you do?

Read rsnapshot/AUTHORS file

### What happened?

I read Benedikt Heine is listed as the current maintainer of rsnapshot, and sent him an email thanking him for his work. He welcomed the email, but let me know he's not been the maintainer for five years.

### What did you expect to happen

The AUTHORS file should at least not list Benedikt Heine as the current maintainer, and if there is one they ought to be listed instead, assuming that's something you want to do.

### My configuration

I have nothing useful to put here.

**Comment by bebehei** [comment]
Oh hi @Hikaru512, yeah I exited the organisation probably in 2020. See the issue #191. I'm currently trying to open a pull request, but have some issues on my side, since my own clone is archived.

**Comment by sgpinkus** [comment]
Good point. Merged #337.
