### ISSUE TITLE
Execution may emit the exitcode 2, which breaks recommended 

### ISSUE THREAD

**Issue by sumpfralle** [rsnapshot/rsnapshot#338]
### Checklist

- [X] I'm reporting a bug
- [X] I've searched the [bugtracker](https://github.com/rsnapshot/rsnapshot/issues) for similar issues, including closed ones.

### What did you do?

I use the `sync_first` for my rsnapshot backups.

### What happened?

I can of see the following lines at the end of a backup operation in my rsnapshot log:
``` 
[2024-04-26T05:18:40] touch /srv/backup/rsnapshot/.sync/
[2024-04-26T05:18:40] rm -f /run/rsnapshot.pid
[2024-04-26T05:18:40] WARNING: /usr/bin/rsnapshot sync: completed, but with some warnings
```

The `WARNING` means, that `rsnapshot` emitted an exitcode 2 (due to files going missing during the backup). According to the man page:

> EXIT VALUES
>
>           0  All operations completed successfully
>
>           1  A fatal error occurred
>
>           2  Some warnings occurred, but the backup still finished

The man page also recommends the following cron job for the `sync` approach:

>           When sync_first is enabled, rsnapshot must first be called with the sync argument, followed by the other usual cron entries. The sync should happen as the lowest, most
>           frequent backup level, and right before. For example:
>
>               0 */4 * * *         /usr/local/bin/rsnapshot sync && /usr/local/bin/rsnapshot alpha

But the `&&` operator fails to work, if the exit code 2 was emitted.

Thus, the rotation was skipped due to the exit code being 2.

### What did you expect to happen

I expected the rotation to happen even in case of spurious rsync-related warnings.

### My configuration

sync 1

### Environment

```markdown
OS: Debian Bullseye
```

### Other information

Currently I work around this with something like the following snippet as the cron job:

```
/usr/bin/rsnapshot sync; result=$?; if [ "$result" = 0 ] || [ "$result" = 2 ]; then rsnapshot beta; fi
```

I could imagine, that there are two ways to improve this situation:
* A) add a configuration setting, which would cause the exit code zero to be emitted even in case of warnings (disabled by default)
* B) always emit the exit code zero (even with warnings)

Reference: this issue was previously [discussed in the mailing list](https://sourceforge.net/p/rsnapshot/mailman/rsnapshot-discuss/thread/20587.1429919019%40ccs.covici.com/) a few years ago.

**Comment by sgpinkus** [comment]
I have the same answer as Stefan from that thread (didn't read all of it) - just run a wrapper if you want to treat a given exit code differently. Example: `(exit 2) || [[ $? -eq 2 ]] && echo continuing with things`. Secondly, if files are vanishing or change while being backed up and you using LVM you could trying using snapshot bit.

**Comment by sgpinkus** [comment]
> This could be worth to be mentioned in the man page?

A brief note about it in the man page would be good. Such a PR would be accepted.
