### ISSUE TITLE
Rsnapshot and risk of silent inconsistent backups

### ISSUE THREAD

**Issue by woodholly** [rsnapshot/rsnapshot#347]
### Checklist

- [X] I'm reporting a bug
- [X] I've searched the [bugtracker](https://github.com/rsnapshot/rsnapshot/issues) for similar issues, including closed ones.

### What did you do?

Rsnapshot internal problem.

### What happened?

Broken backup after reboot or shutdown.

### What did you expect to happen

Rsnapshot should report incomplete transfers.

### My configuration

.

### Other information

Rsnapshot does not store state of transfer, so we have no way to check if snapshot backup is consistent or not. In case of reboot/shutdown, or longer problem with remote server, rsnapshot will fail silently in inconsistent state of backup.
Two ways to solve this problem:
1) create status file with state of each transfer
2) change how rsnapshot works, rsync into daily.temp and rotate snapshots after transfer, not before.

**Comment by floriandeboissieu** [comment]
Enabling `rsync_first` and `link_dest` should behave like the 2nd solution given above, shouldn't it?

**Comment by woodholly** [comment]
What link_dest does? man rsnapshot no info.
Yes, sync_first can be used to script 2. IMHO sync_first  should be enabled by default (not the way it works right now) to prevent this problem.

**Comment by floriandeboissieu** [comment]
`link_dest` uses rsync option --link-dest with the latest snapshot from first level, e.g. alpha.0, to build the hardlinks.

With `link_dest` options enabled, `rsnapshot sync` will give something like this:
```shell
/usr/bin/rsync -a --delete-after --numeric-ids --relative --delete-excluded \                                                                                           
    --link-dest=/backup/alpha.0/test-backup/ \
    /home/me/test-backup/ \
    /backup/.sync/test-backup/ 
```

Without, it would give:
```shell
/usr/bin/rsync -a --delete-after --numeric-ids --relative --delete-excluded \                                                                                           
    /home/me/test-backup/ \
    /backup/.sync/test-backup/ 
```

Both options should be enabled to make it efficient:
1. `link_dest` to harlink `.sync` files with the latest backup (e.g. alpha.0)
2. `sync_first` to include `.sync` in the rotation scheme without making a new synchronization.

**Comment by woodholly** [comment]
Thanks! link_dest is optimization and prevents "cp -al daily.0 .sync" phase of sync_first.
However link_dest has one more important implication, it will prevent increase of the size of incremental backup if reboot/shutdown happens in the middle of "cp -al".

**Comment by woodholly** [comment]
link_dest would not be needed, if "rsnapshot sync"  did  'cp -al' on each subsequent launches (and this can be fixed).

**Comment by DrHyde** [comment]
In an ideal world yes, `sync_first` would be the default. But we're not changing the defaults for software that people have been reliably using for many years for something as important as their backups!

**Comment by woodholly** [comment]
I would advise at least to document this problem and the solution in the documentation.

**Comment by JonMurphy** [comment]
@woodholly - for what it is worth...  You can make the needed changes to the documentation and submit as a pull request.  And yes, I think this should be documented.
