### ISSUE TITLE
proceeds to backup/rotate/delete even though partition not mounted

### ISSUE THREAD

**Issue by AGI-chandler** [rsnapshot/rsnapshot#351]
### Checklist

- [X] I'm reporting a bug
- [X] I've searched the [bugtracker](https://github.com/rsnapshot/rsnapshot/issues) for similar issues, including closed ones.

### What did you do?

👀 Nothing!  What'd you do??

All of our `backup` lines are other partitions (NFS).  The problem/bug arises with the single-directory `backup`'s such as `/projects`.  This is not currently mounted due to issues it's having with its RAID, but `/projects` still exists as an empty directory (mount point) on the _rsnapshot_ server.

On the other hand, if `/archive` isn't mounted, then the `/archive/old_research/` `backup` will cause _rsnapshot_ to throw an error that the "Source directory" "doesn't exist" and halts the process.

### What happened?

Unfortunately, since `/projects` is the only problem right now, _rsnapshot_ proceeds normally, backing up an empty directory, then rotates and deletes old backups.  Before long (15 days), and **without any indication from _rsnapshot_**, our backup data would be rotated and deleted out of existence!  Fortunately I have caught this after 4 days and can stop rsnapshot for now.

### What did you expect to happen

An error and backup halted.

### My configuration

```
config_version		1.2
snapshot_root		/backup/.snapshots
no_create_root		1
cmd_cp			/bin/cp
cmd_rsync		/usr/bin/rsync
cmd_ssh			/usr/bin/ssh
cmd_logger		/usr/bin/logger

retain	daily		15

verbose			3
loglevel		4
logfile			/var/log/rsnapshot.log
lockfile		/var/run/rsnapshot.pid
rsync_short_args	-aFhX
rsync_long_args		--delete-during --info=copy,del,misc2,name,remove,skip,stats3,symsafe --numeric-ids --relative
ssh_args		-o BatchMode=yes
one_fs			1
link_dest		1
sync_first		1
use_lazy_deletes	1
rsync_numtries		10

backup	/data2/				EagI/	exclude=/data2/scratch,exclude=/data2/Globus
backup	/archive/old_research/		Mbo/
backup	/archive/ftp/drosophila/	Mbo/
backup	/data/				Pac/	exclude=/data/scratch
backup	/projects/			Pac/
backup	/projects2/			Pac/
backup	/partner/redwood/		Pac/
backup	/partner/saguaro/		Pac/
backup	/partner/users/			Pac/
```

### Environment

```markdown
OS: Debian 11
Filesystem: ZFS
```

### Other information

I don't think anyone has any reason to backup an empty directory?  Maybe _rsnapshot_ should notice this and at least produce a warning?  Maybe my config is causing this?  Maybe there is a way I can add my own checks that can produce a sufficient warning or error?

**Comment by sgpinkus** [comment]
Checking whether your NFS partitions are mounted is beyond the scope of rsnapshot. I would suggest you do that yourself right before you start your backup.

The actual bug your reporting is more "proceeds to backup/rotate/delete even though target directory empty". I'm sure there are cases where a backup target is empty for some reason. We could add a a warning but don't think it's a pressing issue. 

Note just rsync directly to the remote host avoids the issue and is probably faster.

**Comment by sgpinkus** [comment]
> Whether a partition is mounted or not isn't a sufficient ..  In the current state, /projects is not mounted on the host machine and just an empty dir ...

Do whatever particular pre backup check you want to do outside of rsnapshot.

> Maybe need multiple configs and multiple executions of rsnapshot or something?

Yes, multiple configs and runs. There is kind of a tight coupling between all the `backup` lines in a given config so, in general, you'll find yourself needing to use multiple configs often to solve issues.

**Comment by AGI-chandler** [comment]
> Do whatever particular pre backup check you want to do outside of rsnapshot.

Yo @sgpinkus  Any suggestions how to best do this?

I guess, create a file in the data to be backed up, such as `/projects/.rsnapshot` and then check if that exists before running rsnapshot?

Within the rsnapshot config, looks like there's a few different applicable options.  `cmd_preexec` looks like the one I'd want.  The man says regarding this:
> If the execution fails, rsnapshot will stop immediately.

by "fail" you mean exits with non-zero status right?  So I could make a simple script with just one line like:

`[ -f /projects/.rsnapshot ]`

which  exits with `1` if `/projects/.rsnapshot` isn't there.

Does that all seem alright?  Thanks

**Comment by sgpinkus** [comment]
Yes, you could do it like that. Rsnapshot will return non-zero exit status id preexec fails which may or may not be what you want. The other alternative is just wrap call to rsnapshot in a script that does the checks then chooses whether or not to execute rsnapshot.
