### ISSUE TITLE
lockfile is not being removed when calling `rsnapshot sync` with `use_lazy_deletes = 1`

### ISSUE THREAD

**Issue by myrdd** [rsnapshot/rsnapshot#48]
**how to reproduce:**
  - enable both `use_lazy_deletes` and `sync_first`
  - call `rsnapshot sync`

**what happens:**
  - the lockfile (e.g. `/var/run/rsnapshot.pid`) doesn't get removed.
  - if `rsnapshot sync` is called again subsequently, that command has the warning `WARNING: Removing stale lockfile`. The exit status is then `2` (warning), even if the actual command succeeded.

**what should happen:**
  - the lockfile should have been removed.
  - subsequent commands should not be influenced

This bug has been **introduced by** commit 8147e70.

#### More in detail:

There are two possibilities where the `remove_lockfile()` subroutine is called:

- if `use_lazy_deletes` is **off**: [on line 291](https://github.com/DrHyde/rsnapshot/blob/8147e706d00fb2fcd0c50e95d54b9ffcb1f56932/rsnapshot-program.pl#L291)
- if `use_lazy_deletes` is **active**: [in the `handle_interval()` subroutine, line 2953](https://github.com/DrHyde/rsnapshot/blob/8147e706d00fb2fcd0c50e95d54b9ffcb1f56932/rsnapshot-program.pl#L2953).

However, in the latter case `remove_lockfile()` is called [only in some cases](https://github.com/DrHyde/rsnapshot/blob/8147e706d00fb2fcd0c50e95d54b9ffcb1f56932/rsnapshot-program.pl#L2950), that is, only when the `_delete.$$` directory exists. That directory *does not* exist `rsnapshot sync` is called.

I'm going to create a pull request.

**Comment by myrdd** [comment]
pull request at https://github.com/DrHyde/rsnapshot/pull/49

**Comment by bebehei** [comment]
Thanks for the fix, @myrdd.

**Comment by myrdd** [comment]
Thank you for merging it @bebehei, and also many thanks for all your effort on rsnapshot!
