### ISSUE TITLE
If config-file is a folder, config_version is not found!

### ISSUE THREAD

**Issue by bebehei** [rsnapshot/rsnapshot#51]
bebe@butter > ls
    bin  files  rsnapshot  rsnapshot.conf  rsnapshot.log  testcase
    bebe@butter > rsnapshot -c rsnapshot daily
    Config file "rsnapshot" does not exist or is not readable.
    bebe@butter > ./rsnapshot/bin/rsnapshot -c rsnapshot daily
    ----------------------------------------------------------------------------
    rsnapshot encountered an error! The program was invoked with these options:
    ./rsnapshot/bin/rsnapshot -c rsnapshot daily
    ----------------------------------------------------------------------------
    ERROR: config_version was not defined. rsnapshot can not continue.
    bebe@butter >

rsnapshot is (1.3.1-5 Archlinux, roughly 1.3.1), ./rsnapshot/bin/rsnapshot is built from the current master.

Probably the commit 051d5b5a introduced it. I haven't tested this yet.

**Comment by DrHyde** [comment]
Shouldn't that be ```... -c rsnapshot.conf daily```?

**Comment by DrHyde** [comment]
Ah. The real problem is that in ```parse_config_file``` we assume that ```IO::File->new($not_something_you_can_read_like_a_file)``` returns false if you tell it to do something stupid. But it doesn't:

    $ mkdir foo
    $ perl -MIO::File -e 'print IO::File->new("foo")'
    IO::File=GLOB(0x7fc1f90034f8)

**Comment by bebehei** [comment]
> Shouldn't that be ```... -c rsnapshot.conf daily```?
Jep, this should be, but my tab-completion stopped after rsnapshot. I did not notice it and executed rsnapshot.

    if($current_config_file =~ /^`(.*)`$/) {
        open($CONFIG, "$1 |")
            or bail("Couldn't execute \"$1\" to get config information\n");
    } else {
        $CONFIG = IO::File->new($current_config_file)
      or bail("Could not open config file \"$current_config_file\"\nAre you sure you have permission?");
          }

Just to understand these lines: What do the ticks in the regex? I've never seen a regex with ticks. And I'm pretty sure there is no regex spec with ticks.

What is, if we only use open?

        open($CONFIG, "$1 |")
            or bail("Couldn't execute \"$1\" to get config information\n");

**Comment by DrHyde** [comment]
The backticks are literal characters. It's looking for a command `in backticks`.

That incantation of ```open``` executes the command in ```$1``` (which was captured in the regex above) and gives you a filehandle attached to its STDOUT. It's all so that you can do shell-ish `backtick interpolation` in an ```include_conf``` in the config file.
