### ISSUE TITLE
Development Model?

### ISSUE THREAD

**Issue by sam-at-github** [rsnapshot/rsnapshot#61]
Hey all,

I'm a little bit confused about how things are moving forward in terms development. The CONTRIBUTING.md seems out of sync with the reality.

Last I checked there was talk of taking master back to 1.3.1 and creating a 1.3.2 release. I guess that is not happening now, it would have been a lot of work. So what is the plan? Could we branch a dev from master now, and cut a 1.3.2 release pretty much now, or in a coupe of commits? Maybe create a milestone for 1.3.2.

**Comment by bebehei** [comment]
I plan to release 1.4. I talked to the debian-maintainer and he said, there is no chance, to bring 1.3.2 into stable distro, even if it only contains bugfixes. I interpreted it, that they treat 1.4 and 1.3.2 as the same. And most distros do it the same. 

In #53, we thought about rebasing the old branch and what to do with the old commits between now and 1.3.1. I  thought it would be a good idea starting work from 1.3.1 again, to support the distros in their work, but as I interpreted the debian-maintainer's answer, I thought this will be senseless.

Development is right now **not** out of sync with CONTRIBUTING.md. I just started working on without asking, cause the thread in my PR snoozed for about a month without an answer.

You probably think the development is out of sync right now, cause there is a missing release-branch for rsnapshot 1.3.x. You're right. But I don't want to support the 1.3.x-baseline anymore. There is too much difference in the repository-base. I'll create the first release-branch after 1.4 is released. CONTRIBUTING.md.

**Comment by sam-at-github** [comment]
So summarizing:

 * No 1.3.x straight to 1.4. At some point in the very near future your gonna tag 1.4 and create branch release-1.4. 
 * The master branch is always ahead of release branches, and reps the liveliest code except for features/PRs. No dev branch. (Just like the CONTRIB.md says ;)).

Got it, sounds good.

**Comment by bebehei** [comment]
So summarizing:

>  * No 1.3.x straight to 1.4. At some point in the very near future your gonna tag 1.4 and create branch release-1.4.

Yes. There is also a milestone created in the github-tracker. After we reach this, I'll tag 1.4 and create a seperate release-branch. Right now it is scheduled on June 15

>  * The master branch is always ahead of release branches, and reps the liveliest code except for features/PRs.

Yes!

> No dev branch. (Just like the CONTRIB.md says ;)).

I never mentioned a dev-branch and CONTRIB.md says this neither. You'll merge everything against `master` and branch off everything from `master`.

Where do you read this? I've seen you, mentioning a so-called `dev`-branch, but I thought always, we talk about the same, the only difference I call it `master` and you call it `dev`. Please tell me, what you want to mention with `dev`. Finally we have to resolve this, before further discussion and talking cross purpose.

I'll give you now my understanding of `master`: With master I think it is the branch, where everything is merged together. It is the main branch and the only main branch. In other software-project usually, you have a development branch, where you branch off your features and merge them back in. After a while you merge development into the stable-branch and create from stable-branch your release-branches. But unlike those projects, we only use one branch to branch off new feature-branches and the release-branches. We won't distinguish between a stable branch and a development-branch, we'll only use one branch and call this `master`, cause git's default branch is called by default `master`.

Probably we thought about the same, but expressed in other words.

**Comment by sam-at-github** [comment]
I'm with you. Sorry for confusing the issue. Your description in CONTRIBUTING.md and elsewhere is consistent. I got "dev" from gitflow. That is *all*. I'm just so used to gitflow where master represent latest stable :). My bad for bringing it up.

Someone coming across the code for the first time should have no reason to suppose a dev branch should exists, and the description in the docs is crystal as far as I can see.

**Comment by bebehei** [comment]
You meant this? http://nvie.com/posts/a-successful-git-branching-model/

**Comment by sam-at-github** [comment]
Yep.
