### ISSUE TITLE
official home of project?

### ISSUE THREAD

**Issue by tbussmann** [rsnapshot/rsnapshot#67]
is this repo the official home of the project now? I see quite some recent activity here but the website at http://www.rsnapshot.org seems broken (according to archive.org since early Feb. 2015) and the sourceforge page does not mention GitHub while hosting releases and still active mailing lists. Would be great if someone could confirm the state of the project. Maybe I just came here in a moment of transition?

**Comment by bebehei** [comment]
Yes, this is the so-called official repository. There is no official release done yet, but I'm planning to do so.

The DNS for the website is right now broken, yes. I'm not able to handle this. David Keegel ( @djk20 ) contacted the admin already. We're waiting for an answer.

Sourceforge is still "active" in terms of mailing lists and the mailing-lists will be shut-down, after we find another permanent address to host mailing-lists or comparable solution. Right now on sourceforge there is still the issue/feature/patch-tracker opened. I want to shut this down, too, but before this, I want to merge those reports and look over it, what applies and what not. In short term I want to keep sourceforge-project as minimal as possible and close it on long-term run.

If you have any patches or issue-reports, I would like to see you contributing.

**Comment by tbussmann** [comment]
thank you for the clarification. I'm happy to see things are being taken care of and wish good luck with the project. Will see if I can contribute anything in the future.
