### ISSUE TITLE
Cannot use non-anonymous rsync protocol with username

### ISSUE THREAD

**Issue by oernii** [rsnapshot/rsnapshot#94]
When use this backup config, rsnapshot assumes I want to use ssh:

backup  rsync://oernii@android:/rootfs/        android/

workaround: return 0 in is_ssh_path when the path starts with "rsync://"
sub is_ssh_path {
...
        if ($path =~ m/^rsync:\/\//)    { return (0); }

**Comment by bebehei** [comment]
TBH, I only use the ssh-connection.

> workaround: return 0 in is_ssh_path when the path starts with "rsync://"
> sub is_ssh_path {
> ...
>         if ($path =~ m/^rsync:\/\//)    { return (0); }

this is also done in `is_anon_rsync_path`, but this function is always called **after** `is_ssh_path`.

I'll check this. Thanks for the report.

**Comment by bebehei** [comment]
Errr, do you use the old rsnapshot 1.3.1 release? Please give the output of `rsnapshot --version`. Between 1.3.1 and current master, there is probably already fixed.

**Comment by oernii** [comment]
yep, will try the new one, once it reaches fedora repos :)

# rsnapshot --version
rsnapshot 1.3.1


-- 
+421-2--6241-0360, +421-903--482-603
icq://28153343, skype://oernii-work, jabber://oernii@jabber.org

**Comment by bebehei** [comment]
The linked commit: 5e5bb30435b3690a4cea18ee9cbb27e90ea7ffa9
