### ISSUE TITLE
Copy & Paste?

### ISSUE THREAD

**Issue by Profpatsch** [rsnapshot/rsnapshot#97]
In the region around https://github.com/rsnapshot/rsnapshot/blob/master/rsnapshot-program.pl#L762 I’m like

duuuude, Y U NO refactor?

**Comment by bebehei** [comment]
Dübel geraucht?

**Comment by bebehei** [comment]
Create a PR and I'll merge. IMO this is not a severe bug, it's just the case, that there is a prettier solution to program it.
